<?php echo $this->doctype(); ?>
<html lang="en" class="review">
    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headTitle($this->translate(''));
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        echo $this->headLink()->appendStylesheet($this->assetPath('/styles/' . $this->applicationName() . '.css'));
        echo $this->headScript();
        ?>
    </head>
    <body>
        <h1><?php echo $this->translate($reviewTitle); ?></h1>
        <?php
        $count = 0;
        foreach ($sections as $section):
            $count++;
            ?>
        <div class="review-section">
            <h2><?php echo $count . '. ' . $this->translate($section['header']); ?></h2>
            <?php echo $this->render('partials/read-only/main', $section['config']); ?>
        </div>
        <?php endforeach; ?>
    </body>
</html>
