<table  class="checklist-table">
    <tbody>
        <?php
            foreach ($this->data as $line) {
                echo '<tr>';
                foreach ($line as $cell) {
                    $class = '';
                    if ($cell === $line[count($line) - 1]) {
                        $class = 'class="td--right-aligned"';
                    }
                    if (isset($cell['header']) && $cell['header']) {
                        $openTag = '<th ' . $class . '>';
                        $closeTag = '</th>';
                    } else {
                        $openTag = '<td ' . $class . '>';
                        $closeTag = '</td>';
                    }
                    echo $openTag . $cell['value'] . $closeTag;
                }
                echo '</tr>';
            }
        ?>
    </tbody>
</table>