<?php
echo $this->partial(
    'partials/continuation/checklist-section',
    [
        'data' => $this->licenceChecklist(\Common\RefData::LICENCE_CHECKLIST_TRANSPORT_MANAGERS, $this->data)
    ]
);
?>
<?php if (count($this->data['people']['persons']) > \Common\RefData::CONTINUATIONS_DISPLAY_TM_COUNT) : ?>
    <p>
    <a
        href="<?php echo $this->url(
            'continuation/checklist/transport-managers',
            ['continuationDetailId' => $this->data['continuationDetailId']])
        ; ?>"
        class="action--secondary large" target="_blank">
        <?php echo $this->translate('continuations.transport-managers.button-label'); ?>
    </a>
    </p>
    <p><?php echo $this->translate('continuations.checklist.section.opens_in_a_new_window'); ?></p>
<?php endif; ?>

