<?php
echo $this->partial(
    'partials/continuation/checklist-section',
    [
        'data' => $this->licenceChecklist(\Common\RefData::LICENCE_CHECKLIST_OPERATING_CENTRES, $this->data)
    ]
);
?>
<?php
if (
    count($this->data['operatingCentres']['operatingCentres'])
    > \Common\RefData::CONTINUATIONS_DISPLAY_OPERATING_CENTRES_COUNT
) :
?>
    <p>
    <a
    href="<?php echo $this->url(
        'continuation/checklist/operating-centres', ['continuationDetailId' => $this->data['continuationDetailId']])
    ; ?>"
    class="action--secondary large" target="_blank">
    <?php echo $this->translate('continuations.operating-centres.button-label'); ?>
    </a>
    </p>
    <p><?php echo $this->translate('continuations.checklist.section.opens_in_a_new_window'); ?></p>
<?php endif; ?>
<h3><?php echo $this->translate('continuations.authorisation.label'); ?></h3>
<?php echo $this->partial(
    'partials/continuation/checklist-section',
    [
        'data' => $this->licenceChecklist(\Common\RefData::LICENCE_CHECKLIST_OPERATING_CENTRES_AUTHORITY, $this->data)
    ]
);

