<p><b>Translated to Welsh</b></p><details class="help">
    
    <summary class="help__summary">
        What's the difference?
    </summary>

    <div class="article help__text">
        
        <h3>Goods vehicles</h3>

        <p>Goods vehicles have either:</p>
        
        <ul>
            <li>a gross plated weight of more than 3,500kg</li>
            <li>an unladen weight of more than 1,525kg (where there’s no plated weight)</li>
        </ul>
    
        <p>Read more about <a href="https://www.gov.uk/being-a-goods-vehicle-operator/overview" target="_blank">being a goods vehicle operator</a> and <a href="https://www.gov.uk/vehicle-weights-explained" target="_blank">goods vehicle weights</a>.</p>
            
        <h3>Public service vehicles</h3>
        
        <p>Public service vehicles (PSVs) are either:</p>
        
        <ul>
            <li>vehicles used for hire or reward that can carry 9 or more passengers</li>
            <li>smaller vehicles used to carry passengers and charge them separate fares</li>
        </ul>
    
        <p>Read more about <a href="https://www.gov.uk/psv-operator-licences" target="_blank">PSV operator licences</a>.</p>

        <h3>Other rules and exemptions</h3>
        
        <p>There are different <a href="http://www.nidirect.gov.uk/index/information-and-services/motoring/driving-for-a-living/goods-vehicle-operator-licensing.html" target="_blank">rules in Northern Ireland</a>.</p>
        
        <p>Some types of vehicles don't need an operator's licence. Read more about <a href="https://www.gov.uk/being-a-goods-vehicle-operator/exemptions" target="_blank">exemptions</a>.</p>
        
    </div>
    
</details>