<div class="gem-c-govspeak govuk-govspeak govuk-!-margin-top-7" data-module="govspeak">
    <h2 class="govuk-heading-m" style="font-size: 24px !important">Cwcis trydydd parti</h2>
    <p>Cwcis yw'r rhain a osodir ar eich cyfrifiadur gan wefannau allanol y defnyddir eu gwasanaethau ar wefan Trwyddedu Gweithredwyr Cerbydau.</p>

    <h3 class="govuk-heading-s govuk-!-margin-top-6" id="messages-across-govuk">GOV.UK Dilysu</h3>
    <p>Rydym yn defnyddio GOV.UK Dilysu i atal twyll hunaniaeth, diogelu preifatrwydd defnyddwyr a sicrhau ein bod yn rhoi mynediad i'r bobl iawn i'n gwasanaeth. Mae'r GOV.UK Dilysu yn defnyddio  <a href="{{URL_VERIFY_COOKIE}}" target="_blank" rel="external noreferrer noopener">cwcis ychwanegol <?php echo $this->escapeHtml($this->translate('link.opens-new-window')); ?></a> i olrhain eu gwefan.</p>

    <h3 class="govuk-heading-s govuk-!-margin-top-6" id="messages-across-govuk">Capita Pay360</h3>
    <p>Caiff taliadau Trwyddedu Gweithredwyr Cerbydau eu cynnal gan <a href="{{URL_PAY_360}}" target="_blank">Capita Pay 360</a>. Mae Capita yn defnyddio  <a href="{{URL_PAY_360_COOKIE}}" target="_blank" rel="external noreferrer noopener">cwcis ychwanegol <?php echo $this->escapeHtml($this->translate('link.opens-new-window')); ?></a> i olrhain eich cynnydd ar eu gwefan.</p>

    <h3 class="govuk-heading-s govuk-!-margin-top-6" id="messages-across-govuk">SmartSurvey</h3>
    <p>Defnyddiwn <a rel="external" href="{{URL_SMART_SURVEY}}" target="_blank">SmartSurvey</a> i gael adborth am foddhad gwasanaethau. Os cymerwch ran, bydd SmartSurvey <a rel="external noreferrer noopener" href="{{URL_SMART_SURVEY_COOKIE}}" target="_blank"> yn cadw cwcis ychwanegol <?php echo $this->escapeHtml($this->translate('link.opens-new-window')); ?></a> i olrhain eich cynnydd ar eu gwefan.</p>
</div>
