<div class="gem-c-govspeak govuk-govspeak govuk-!-margin-top-7" data-module="govspeak">
    <h2 class="govuk-heading-m" style="font-size: 24px !important">Cyfeiriadau IP</h2>
    <p>Mae Trwyddedu Gweithredwyr Cerbydau yn casglu cyfeiriad IP i olrhain ac i gydgrynhoi gwybodaeth nad yw'n bersonol. Er enghraifft, mae'r gwasanaeth yn defnyddio cyfeiriadau IP i fonitro tueddiadau, rhanbarthau lle mae defnyddwyr yn llywio'r wefan a'r tudalennau yr ymwelwyd â nhw.</p>
    <p>Allwn ni ddim defnyddio eich cyfeiriad IP i'ch adnabod chi'n bersonol.</p>
</div>
