<details class="help">
    <summary class="help__summary"> Beth yw'r gwahaniaeth?</summary>
    <div class="article help__text"><h3>Cerbydau nwyddau</h3>
        <p>Mae gan gerbydau nwyddau naill ai:</p>
        <ul>
            <li>pwysau plât gros o fwy na 3,5cg</li>
            <li>pwysau di-lwyth o fwy na 1,525cg (lle nad oes pwysau plât)</li>
        </ul>
        <p>Darllenwch ragor ynghylch <a href="http://gov.uk/being-a-goods-vehicle-operator" target="_blank">bod yn
                weithredwr cerbyd nwyddau</a> a <a href="https://www.gov.uk/vehicle-weights-explained" target="_blank">pwysau
                cerbyd nwyddau</a>.</p>
        <h3>Cerbydau gwasanaeth cyhoeddus</h3>
        <p>Mae cerbydau gwasanaeth cyhoeddus (PSVs) naill ai'n:</p>
        <ul>
            <li>gerbydau a ddefnyddir ar log neu er elw sy'n gallu cludo 9 teithiwr neu fwy</li>
            <li>cerbydau llai a ddefnyddir i gludo teithwyr a chodi tocynnau ar wahân arnynt</li>
        </ul>
        <p>Darllenwch ragor ynghylch <a href="https://www.gov.uk/psv-operator-licences" target="_blank">trwyddedau
                gweithredwr PSV</a>.</p>
        <h3>Rheolau ac esemptiadau eraill</h3>
        <p>Mae rheolau gwahanol <a
                href="http://www.nidirect.gov.uk/index/information-and-services/motoring/driving-for-a-living.htm"
                target="_blank">yng Ngogledd Iwerddon</a>.</p>
        <p>Some types of vehicles don't need an operator's licence. Read more about <a
                href="https://www.gov.uk/being-a-goods-vehicle-operator/exemptions" target="_blank">exemptions</a>.</p>
    </div>
</details>
