<p>Mae gan gytundeb Norwy ofynion gwahanol bob cyfnod. Bydd y trwyddedau i chi wneud cais ar gael yn unol â hynny.</p>
<h2 class="govuk-heading-s">Ar gael nawr</h2>
<p>Rhwng 1 Ionawr 2021 a 30 Medi 2021, dim ond os ydych chi'n cynnal cabotage y bydd angen trwyddedau arnoch chi. Yn ystod y cyfnod hwn, rhaid i chi ddefnyddio trwyddedau cabotage ynghyd â Thrwydded y DU ar gyfer y Gymuned.</p>
<h2 class="govuk-heading-s">Ar gael ganol 2021</h2>
<p>O 1 Hydref 2021 ymlaen, bydd angen caniatâd safonol arnoch os ydych am ddod i mewn i'r wlad a thrwydded cabotage ychwanegol i gynnal cabotage. O'r pwynt hwn ymlaen rhaid defnyddio pemit cabotage ynghyd â thrwydded safonol i fod yn ddilys.</p>
<p>Mae trwyddedau Norwy yn ddilys o'r diwrnod y cânt eu rhoi tan 31 Ionawr y flwyddyn ganlynol.</p>
<?php echo $this->translate('markup-irhp-essential-information-cabotage'); ?>
<?php echo $this->partial('partials/irhp-bilateral-fee-table'); ?>
