<p><b>Translated to Welsh</b></p><h3>Next step</h3>

<p>
    The Transport Manager should provide the licenced operator with a completed TM1 form for them to
    co-sign and return to the Central Licensing Office.
    <a href="https://www.gov.uk/government/publications/application-to-add-a-transport-manager-to-a-licence-tm1" target="_blank">View TM1 form</a>
</p>

<p><?php echo $this->partial('partials/office-address')?></p>

<h3 class="important">Important</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sagittis dictum tortor, nec ornare metus ultrices eget. Curabitur et consectetur nunc. Quisque ligula metus, ultrices eu urna sit amet, cursus egestas nulla. Suspendisse sodales facilisis massa vel consectetur. Maecenas viverra bibendum eros. Pellentesque pellentesque enim nec nisi varius rhoncus. Nam condimentum a dui non fermentum. Donec lobortis leo vitae urna bibendum auctor.</p>