Darllen rhagor am
<span id="typeOfLicence-hint-goods">
    <a
        href="https://www.gov.uk/being-a-goods-vehicle-operator/types-of-licence"
        target="_blank"
        aria-label="Darllen rhagor am mathau o drwydded"
    >
        mathau o drwydded
    </a>
</span>
<span id="typeOfLicence-hint-psv">
    <a
        href="https://www.gov.uk/psv-operator-licences"
        target="_blank"
        aria-label="Darllen rhagor am mathau o drwydded"
    >
        mathau o drwydded
    </a>
</span>
.