<h2 class="govuk-heading-l">International Road Haulage Permits</h2>
<details class="govuk-details" %s>
    <summary class="govuk-details__summary">
        <span class="govuk-details__summary-text">
            How to apply for permits
        </span>
    </summary>
    <div class="govuk-details__text">
        If you want to transport goods internationally, you can apply for a permit.<br/>
        Further <a href="{{ECMT_PERMITS_GUIDANCE_LINK}}">guidance</a>
        on permits is available on GOV.UK
    </div>
</details>
