<ul class="govuk-list govuk-list--bullet">
    <li>wedi darllen a chytuno i ddilyn <a href="<?php echo $this->translate('permits.link.ecmt.guidance') ?>" target="_blank">y rheolau ar sut i ddefnyddio trwyddedau ECMT<span class="govuk-visually-hidden">(dolen yn agor mewn ffenestr newydd)</span></a></li>
    <li>yn defnyddio cerbydau sy'n cydymffurfio â safon allyriadau'r Ewro ar gyfer pob trwydded yn unig</li>
    <li>deall a roddir trwydded, gall eithrio teithio i Awstria, Gwlad Groeg, Hwngari, yr Eidal a Rwsia gan mai nifer cyfyngedig o drwyddedau sydd ar gyfer teithio i'r gwledydd hyn</li>
    <li>gwblhau'r llyfr log cyfatebol gyda manylion taith lawn cyn dechrau taith</li>
    <li>deall bod angen Tystysgrif Cydymffurfio a Thystysgrif diogelwch ar y ffyrdd ar gyfer pob cerbyd a threlar rydych yn bwriadu ei ddefnyddio</li>
</ul>
<p class="govuk-body">Rhaid i'ch gyrrwr hefyd gario'r drwydded a'r llyfr log cyfatebol, a'r tystysgrifau ar gyfer y siwrnai allan a dychwelyd gyfan a'i chyflwyno i unrhyw awdurdod cymwys neu arolygwyr.</p>
