<p>Gwiriwch eich bod wedi defnyddio’r cyfeiriad cywir ar gyfer y wefan.</p>
<p>Os credwch eich bod wedi canfod cyswllt e-bost nad yw’n gweithio<a href="mailto:notifications@vehicle-operator-licensing.service.gov.uk">notifications@vehicle-operator-licensing.service.gov.uk</a></p>
<p>Gadewch i ni wybod:</p>
<ul>
    <li>pa dudalen oeddech chi arni</li>
    <li>a beth oeddech chi’n ei geisio ei wneud</li>
    <?php if (!empty($correlationId)): ?>
        <li>gan ddyfynnu cyfeirnod <?php echo $this->escapeHtml($correlationId); ?></li>
    <?php endif; ?>
</ul>