<h2 class="govuk-heading-l">CY - International Road Haulage Permits</h2>
<details class="govuk-details" %s>
    <summary class="govuk-details__summary">
        <span class="govuk-details__summary-text">
            CY - How to apply for permits
        </span>
    </summary>
    <div class="govuk-details__text">
        CY - If you want to transport goods internationally, you can apply for a permit.<br/>
        Further <a href="https://www.gov.uk/guidance/international-authorisations-and-permits-for-road-haulage">guidance</a>
        on permits is available on GOV.UK
    </div>
</details>
