<p class="govuk-body">Byddwch yn derbyn e-bost i gadarnhau ein bod wedi derbyn eich cais.</p>
<p class="govuk-body">Mae'ch cais am drwydded yn cael ei ystyried a bydd yn cael ei brosesu nawr. Efallai y byddwn yn cysylltu â chi i wirio'ch cais. Byddwn yn rhoi gwybod i chi am ganlyniad eich cais cyn pen 10 diwrnod gwaith.</p>
<p class="govuk-body">Gallwch wirio statws eich cais ar y dudalen nesaf.</p>
