<details class="govuk-details" data-module="govuk-details">
    <summary class="govuk-details__summary">
        <span class="govuk-details__summary-text">
            Helpwch i gyfrifo'ch teithiau rhyngwladol
        </span>
    </summary>
    <div class="govuk-details__text">
        <p class="govuk-body-l">Mae angen i chi ddweud wrthym am bob siwrnai ddwyffordd sy'n:</p>
        <h4 class="govuk-heading-s">Dechreuwch a gorffen y tu mewn i'r DU a mynd i neu basio trwy unrhyw wlad yn yr UE a / neu Wlad yr Iâ, Liechtenstein a Norwy</h4>
        <p class="govuk-body">Er enghraifft: Mae eich lori yn gadael y DU, yn gyrru drwy Ffrainc, yr Almaen a Gwlad Pwyl i gyrraedd Wcráin ac yn dychwelyd trwy Hwngari, Awstria, y Swistir a Ffrainc. Mae hyn yn cael ei gyfrif fel un daith ryngwladol.</p>
        <hr class="govuk-section-break govuk-section-break--m govuk-section-break--visible">
        <h4 class="govuk-heading-s">Dechrau a gorffen y tu allan i'r DU ond y tu mewn i unrhyw wlad yn yr UE, Gwlad yr Iâ, Liechtenstein neu Norwy</h4>
        <p class="govuk-body">Er enghraifft: Mae eich tryc yn gadael y DU, yn gyrru trwy Ffrainc, Gwlad Belg a'r Swistir i gyrraedd Liechtenstein ac yn dychwelyd trwy Awstria, yr Almaen, y Swistir, yr Eidal a Ffrainc. Mae hyn hefyd yn cael ei gyfrif fel un siwrnai ryngwladol.</p>
        <hr class="govuk-section-break govuk-section-break--m govuk-section-break--visible">
        <h4 class="govuk-heading-s">Dechrau a gorffen y tu allan i unrhyw rai o'r gwledydd a restrwyd uchod ond mae eich taith yn mynd drwy unrhyw rai o'r gwledydd hyn</h4>
        <p class="govuk-body">Er enghraifft: Mae eich lori yn gyrru i Iwerddon i godi nwyddau, yn gyrru drwy'r DU a Ffrainc i gyrraedd Sbaen ac yn dychwelyd trwy Ffrainc i'r DU. Mae hyn yn cael ei gyfrif fel un daith ryngwladol.</p>
    </div>
</details>
