<p><b>Translated to Welsh</b></p><details class="help">
  <summary class="help__summary">
    What's the difference?
  </summary>
  <div class="help__text">
    <p>Goods vehicles have either:</p>
    <ul>
      <li>a gross plated weight of more than 3,500kg</li>
      <li>an unladen weight of more than 1,525kg (where there’s no plated weight)</li>
    </ul>
    <p>Read more about <a href="https://www.gov.uk/being-a-goods-vehicle-operator/overview" target="_blank">being a goods vehicle operator</a> and <a href="https://www.gov.uk/vehicle-weights-explained" target="_blank">goods vehicle weights</a></p>
    <p>Public service vehicles (PSVs) are either:</p>
    <ul>
      <li>vehicles used for hire or reward that can carry 9 or more passengers</li>
      <li>smaller vehicles used to carry passengers and charge them separate fares</li>
    </ul>
    <p><a href="https://www.gov.uk/psv-operator-licences" target="_blank">Read more about PSV operator licences</a></p>
    <p>There are different <a href="http://www.nidirect.gov.uk/index/information-and-services/motoring/driving-for-a-living/goods-vehicle-operator-licensing.html" target="_blank">rules in Northern Ireland</a> and some types of vehicle don’t need an operator’s licence.</p>
    <p><a href="https://www.gov.uk/being-a-goods-vehicle-operator/exemptions" target="_blank">Read more about exemptions</a></p>
  </div>
</details>