<p class="govuk-hint">Mae'r cwcis hyn yn hanfodol er mwyn eich galluogi i ddechrau defnyddio'r gwasanaeth, symud o gwmpas y wefan a defnyddio ei nodweddion. Heb y cwcis hyn, ni ellir darparu'r gwasanaethau yr hoffech eu defnyddio.</p>
<p class="govuk-hint">Mae angen iddynt fod ymlaen bob amser.</p>
<p class="govuk-hint">
  <a href="<?php echo $this->url('cookies')?>" class="govuk-link" data-module="track-click" data-track-category="cookieSettings" data-track-action="Find out more about cookies">
        Dysgwch fwy am gwcis ar y gwasanaeth Trwyddedu Gweithredwyr Cerbydau
    </a>
</p>
