<?php
$header[] = ['value' => $this->translate('continuations.vehicles-section.table.vrm'), 'header' => true];
if ($this->vehicles['isGoods']) {
    $header[] = ['value' => $this->translate('continuations.vehicles-section.table.weight'), 'header' => true];
}
$vehicleData[] = $header;
$vehicles = $this->vehicles['vehicles'];
if (is_array($vehicles) && count($vehicles) <= $this->vehicles['displayVehiclesCount']) {
    foreach ($vehicles as $vehicle) {
        $row = [];
        $row[] = ['value' => $vehicle['vrm']];
        if ($this->vehicles['isGoods']) {
            $row[] = ['value' => $vehicle['weight']];
        }
        $vehicleData[] = $row;
    }
}
?>
<?php echo $this->partial('partials/checklist-section', ['data' => $vehicleData]); ?>
