<div class="actions-container article declaration">
    <div class="field">
        <p>CY - By continuing you confirm that:</p>
    </div>
    <ul class="list-bullet">
        <li>cy - the information you’ve given is correct</li>
        <li>cy -you will not carry out cabotage. </li>
        <li>cy - your vehicle meets Euro 6 emissions standards.</li>
        <li>cy - you agree with the <a href="">terms and conditions</a>.</li>
        <li>cy - you’ve read the ECMT permits <a href="https://www.gov.uk/guidance/international-authorisations-and-permits-for-road-haulage#european-conference-of-ministers-of-transport-emct-multilateral-road-haulage-permits" target="blank">Guidance notes.</a> </li>
    </ul>
</div>
