<h4>Goods Variation application involving an upgrade from restricted to standard
national/international (GV80A)</h4>

<p><strong> I understand that by submitting this application I am accepting the additional
undertakings below; that they will be recorded on the licence; that failure to
comply with the conditions or undertakings recorded on the licence may result
in the licence being revoked, suspended or curtailed; and that failure to
comply with these conditions is also a criminal offence.</strong></p>

<ul>
  <li>I must be able to prove that I have a formal arrangement for access at all
  times to at least one vehicle registered or in circulation in GB. This could
  be by specifying a vehicle for use under an O-licence or by demonstrating on
  request that I (the licence holder) has a vehicle available – so vehicles may
  be either wholly owned or held under a hire-purchase, hire/leasing arrangement
  or other type of formal arrangement.</li>

  <li>I have an establishment in Great Britain (GB) with premises in which I keep
  core business documents. These include (as a minimum) accounting and personnel
  management documents and data on driving time and rest. I understand that the
  use of a PO Box or third party address is not permitted.</li>
</ul>