<p><b>Translated to Welsh</b></p><p>Becuase the Transport Manager doesn't have an email address they'll have to:.</p>
<ul>
    <li><a href="<?php echo $this->translate('TM1_FORM_LINK') ?>" download>print out a TM1 form</a></li>
    <li>co-sign it with an owner or business director</li>
    <li>return it to the Central Licensing Office</li>
</ul>
<p>We’ll let you know when we’ve received their form.</p>

<h3 class="important">Important</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur voluptatum suscipit dolorem facere, id quae est! Possimus ipsa tempore libero!</p>