<ul class="govuk-list govuk-list--bullet">
    <li>rydych wedi darllen y  <a href="{{ECMT_PERMITS_GUIDANCE_LINK}}" target="_blank">nodiadau cyfarwyddyd</a> ar sut i ddefnyddio hawlenni cludo nwyddau rhyngwladol.</li>
    <li>byddwch yn cydymffurfio'n llawn â'r amodau defnyddio a'r telerau a'r amodau y gellir defnyddio'r hawlenni oddi danynt.</li>
    <li>bydd eich gyrrwr yn cario'r hawlen ar gyfer y daith gyfan allan a'r daith yn ôl a'i chyflwyno i unrhyw awdurdod cymwys neu arolygwyr.</li>
    <li>rydych yn deall bod angen un hawlen ar gyfer pob cerbyd rydych yn bwriadu ei ddefnyddio i gludo nwyddau i ac o unrhyw wlad yn yr UE neu'r AEE.</li>
</ul>
