<p><b>Translated to Welsh<b></p><details class="help">
  <summary class="help__summary">
    How is the financial evidence calculated?
  </summary>
  <div class="help__text">
    <p>
      Standard national and international licence applicants will be required to demonstrate
      £<?php echo number_format($standardFirst); ?>
      for the first vehicle and
      £<?php echo number_format($standardAdditional); ?>
      for each additional vehicle they request to be authorised.
    </p>
    <p>
      The rates for restricted licence holders and applicants are
      £<?php echo number_format($restrictedFirst); ?>
      for the first vehicle and
      £<?php echo number_format($restrictedAdditional); ?>
      for each additional authorised vehicle.
    </p>
  </div>
</details>