<div class="article">
    <div class="guidance">
    <p>Er mwyn derbyn trwydded mae angen ichi brofi bod gennych ddigon o arian i gadw’ch cerbydau a rhedeg eich busnes.</p>

    <p>Darllen rhagor am <a href="<?php echo $this->url('guides/guide', ['guide' => 'financial-evidence']) ?>" target="_blank">sut i ddarparu tystiolaeth ariannol</a>.</p>
    </div>

    <div class="info-box info-box--grey info-box--large-padding">
        <h3>Faint fydd arnoch ei angen?</h3>

        <h2 style="margin-top: 0;">&pound; <?php echo number_format($requiredFinance); ?></h2>

        <p>Seilir y ffigur hwn ar:</p>
        <ul>
            <li>Y cais hwn ar gyfer <?php echo $applicationVehicles; ?> cerbyd<?php echo $applicationVehicles != 1 ? 'au' : ''; ?></li>
            <?php if ((int) $otherLicenceVehicles > 0): ?>
                <li>maintenance of <?php echo $otherLicenceVehicles; ?> vehicle<?php echo $otherLicenceVehicles != 1 ? 's' : ''; ?> on your other licence(s)</li>
            <?php endif; ?>
            <?php if ((int) $otherApplicationVehicles > 0): ?>
                <li>your other application(s) for <?php echo $otherApplicationVehicles; ?> vehicle<?php echo $otherApplicationVehicles != 1 ? 's' : ''; ?></li>
            <?php endif; ?>
        </ul>

        <p>
            <details class="govuk-details" data-module="govuk-details">
                <summary class="govuk-details__summary" aria-controls="details-content-how-calculated">
                    <span class="govuk-details__summary-text">
                        Sut wnaethom amcangyfrif hwn?
                    </span>
                </summary>
                <div class="govuk-details__text" id="details-content-how-calculated">
                    <p>For standard national and international licences you must have:</p>
                    <ul class="govuk-list govuk-list--bullet">
                        <li>&pound;<?php echo number_format($standardFirst); ?> for the first vehicle</li>
                        <li>&pound;<?php echo number_format($standardAdditional); ?> for each additional vehicle</li>
                    </ul>
                    <p>For restricted licences you must have:</p>
                    <ul class="govuk-list govuk-list--bullet">
                        <li>&pound;<?php echo number_format($restrictedFirst); ?> for the first vehicle</li>
                        <li>&pound;<?php echo number_format($restrictedAdditional); ?> for each additional vehicle</li>
                    </ul>
                </div>
            </details>
        </p>
    </div>
</div>