<div class="govuk-phase-banner">
  <p class="govuk-phase-banner__content">
    <strong class="govuk-tag govuk-phase-banner__content__tag">
  beta
</strong>
    <span class="govuk-phase-banner__text">
      <a class="govuk-link" href="{{URL_SMART_SURVEY_IN_PAGE}}" aria-label="Helpwch ni i wella'r gwasanaeth hwn" target="_blank">
        Beth oedd eich barn am y gwasanaeth hwn?<span class="govuk-visually-hidden">(dolen yn agor mewn ffenestr newydd)</span>
      </a> (yn cymryd 30 eiliad)
    </span>
  </p>
</div>

