<p>
    CY - <a href="https://www.gov.uk/cabotage" target="_blank">Cabotage </a>is the haulage and moving of goods for hire or reward between 2 points in the same country carried out by a vehicle that is not registered in that country.
</p>

<div class="form-group panel panel-border-wide">
    <p>CY - If road haulage cabotage operations is part of your activities, you may consider applying for a <a href="">bilateral permit.</a></p>
</div>