Rydym yn defnyddio Google Analytics i fesur sut rydych yn defnyddio'r wefan er mwyn i ni allu ei gwella yn seiliedig ar anghenion defnyddwyr. Nid ydym yn caniatáu i Google ddefnyddio neu rannu'r data am sut rydych yn defnyddio'r safle hwn.<br><br>

Mae Google Analytics yn gosod cwcis sy'n storio gwybodaeth ddienw am:
<ul>
    <li>sut y cawsoch chi'r safle</li>
    <li>y tudalennau rydych yn ymweld â nhw wrth ddefnyddio'r gwasanaeth hwn, a faint o amser rydych yn ei dreulio ar bob tudalen</li>
    <li>Beth rydych chi'n clicio arno tra byddwch yn ymweld â'r safle</li>
</ul>
