<h2 class="govuk-heading-m govuk-!-margin-top-7" style="font-size: 24px !important">Cwcis sy'n cofio eich gosodiadau</h2>
<p>Mae'r cwcis hyn yn gwneud pethau fel cofio eich hoffterau a'r dewisiadau rydych yn eu gwneud, i bersonoli eich profiad o ddefnyddio'r gwasanaeth.</p>
<table style="font-size: 16px;">
    <tbody>
    <tr>
        <th>Enw</th>
        <th>Diben</th>
        <th>Daw i ben</th>
    </tr>
    </tbody>
    <tbody>
    <tr>
        <td>langPref</td>
        <td>Defnyddio i storio eich dewis iaith gyfredol (Cymraeg neu Saesneg)</td>
        <td>10 mlynedd</td>
    </tr>
    </tbody>
</table>
