<p class="field">Bydd angen ichi hysbysebu'r cais mewn papur newyddion lleol ac anfon copi i ni. Gwelwch ein canllawiau ar <a href="%s" target="_blank">sut i hysbysebu'ch cais</a>.</p>

<p class="legend">Sut hoffech chi anfon eich hysbyseb?</p>
<!-- welsh translation needs adding here:
<p class="form-hint">Uploading your financial information as soon as possible will help us process your application quickly.</p>-->