<p><b>Translated to Welsh<b></p><h3>Approve and submit online</h3>

<p>
    The Licenced Operator must review and approve the Transport Manager form<br>
    <a href="%s" target="_blank">Review form</a>
</p>

<div class="verify">
    <p>
        Registering with GOV.UK VERIFY will allow the Licensed Operator to submit the Transport Manager form online
    </p>

    <div class="actions-container">
        <a href="?register=opsigned" class="action--verify">Register for verify</a> <a href="">I already have an account</a>
    </div>

</div>

<h3 class="important">Important</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sagittis dictum tortor, nec ornare metus ultrices eget. Curabitur et consectetur nunc. Quisque ligula metus, ultrices eu urna sit amet, cursus egestas nulla. Suspendisse sodales facilisis massa vel consectetur. Maecenas viverra bibendum eros. Pellentesque pellentesque enim nec nisi varius rhoncus. Nam condimentum a dui non fermentum. Donec lobortis leo vitae urna bibendum auctor.</p>