<!-- SIDE PANEL -->
<div class="one-third">
    <aside class="sidebar" role="complementary">
        <div class="info-box info-box--grey">
            <h3 class="info-box__heading">CY - Permit status</h3>
            <p class="info-box__icon-wrapper info-box__text">
                <i class="info-box__icon selfserve-important"></i>%s
                <br/>CY - Due by %s
            </p>
        </div>
        <div class="info-box info-box--blue">
            <h3 class="info-box__heading">CY - Permits will be valid</h3>

            <p class="info-box__text">
                CY - From
                <br/>
                <strong>%s</strong>
            </p>
            <p class="info-box__text">
                CY - To
                <br/>
                <strong>%s</strong>
            </p>
        </div>

    </aside>
</div>