<h2 class="govuk-heading-m govuk-!-margin-top-7" style="font-size: 24px !important">Cwcis diogelwch</h2>
<p>Cwcis parti cyntaf yw'r rhain a bennir gan wasanaeth trydydd parti a ddefnyddiwn i diogelu ein gwasanaeth. Maent yn helpu i nodi gweithgarwch maleisus a diogelu data. Byddant yn casglu gwybodaeth mewn ffurf ddienw heb storio unrhyw wybodaeth bersonol.</p>

<table style="font-size: 16px;">
    <thead>
    <tr>
        <th scope="col">Enw</th>
        <th scope="col">Diben</th>
        <th scope="col">Daw i ben</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td>incap_ses_{ID}</td>
            <td>Ddefnyddir gan fur cadarn y cymhwysiad gwe i gysylltu ceisiadau HTTP ag ymweliad penodol a gwella diogelwch y wefan, gan ei diogelu rhag ymosodiad</td>
            <td>Pan fyddwch yn cau eich porwr</td>
        </tr>
        <tr>
            <td>nlbi_{ID}</td>
            <td>Defnyddir gan y llwyfan cyflwyno, i sicrhau bod ceisiadau gan ddefnyddiwr yn cael eu hanfon at yr un gweinydd tarddiad</td>
            <td>Pan fyddwch yn cau eich porwr</td>
        </tr>
        <tr>
            <td>visid_incap_{ID}</td>
            <td>Fe'i defnyddir i gysylltu sesiynau â dyfais ymwelydd penodol ac fe'i defnyddir gan fur cadarn y rhaglen we i wella diogelwch y wefan a'i diogelu rhag ymosodiad</td>
            <td>1 flwyddyn</td>
        </tr>
        <tr>
            <td>_utmvm{ID}<br>_ utmva<br>__utmvb{ID}</td>
            <td>Mae'r cwcis parti cyntaf hyn yn cael eu gosod gan wasanaeth trydydd parti i hidlo ceisiadau maleisus.</td>
            <td>15 munud</td>
        </tr>
        <tr>
            <td>__utmvc</td>
            <td>Caiff y cwcis parti cyntaf hyn eu gosod gan wasanaeth trydydd parti i hidlo ceisiadau maleisus</td>
            <td>15 munud</td>
        </tr>
    </tbody>
</table>
