<p><b>Translated to Welsh</b></p>
  <div class="article">
    <h3 class="important">Important</h3>
    <p><b>Please note:</b> fees are non-refundable</p>
    <p>You must update your licence record if the details on your operator licence have changed.</p>
    <p>Please complete your continuation document and return it to us before your continuation fee due date. If you don’t send your signed document in on time, your licence will expire, even if you have paid the fee.</p>
  </div><!-- .article -->