<p><b>Translated to Welsh</b></p><h3>Laws</h3>
<p>Operator licensing in the UK is covered by laws including:</p>
<ul>
    <li>the Goods Vehicle Licensing of Operators Act 1995</li>
    <li>the Public Passenger Vehicles Act 1981 (as amended)</li>
    <li>the Goods Vehicles (Licensing of Operators) Act (Northern Ireland) 2010</li>
</ul>

<h3>Permission</h3>
<p>This service is only for operators and representatives with permission to use it. If you don’t know whether you have permission email <a href="mailto:operatorlicensing@otc.gov.uk">operatorlicensing@otc.gov.uk</a>.</p>

<h3>Access to the website</h3>
<p>We may refuse to carry out or allow transactions if we’re not sure about:</p>
<ul>
    <li>the identity or authority of anybody who tries to make them</li>
    <li>whether the transaction’s legal</li>
</ul>

<h3>Your password and user ID</h3>
<p>If you think someone else has your information, or they’re being misused, change your password straight away and email <a href="mailto:mailto:operatorlicensing@otc.gov.uk">operatorlicensing@otc.gov.uk</a>.</p>
<p>You aren’t liable for misuse of your password or username before you receive them, or after you’ve told us that they’re being misused.</p>

<h3>When we might terminate or withdraw your password and ID</h3>
<p>We may terminate or suspend your right to use a password or username at any time. Unless we feel more urgent action’s necessary, we’ll give you at least seven days’ notice.</p>
<p>We may also withdraw your password or ID:</p>
<ul>
    <li>if there have been too many attempts to log in using an incorrect password or ID (email <a href="mailto:operatorlicensing@otc.gov.uk">operatorlicensing@otc.gov.uk</a> if this happens)</li>
    <li>if we think it’s necessary for security reasons</li>
    <li>to stop your licence being misused</li>
    <li>the terms of use have been broken</li>
</ul>

<h3>Virus protection</h3>
<p><a href="https://www.gov.uk/help/terms-conditions">See the GOV.UK terms and conditions</a></p>

<h3>Personal information we collect about you</h3>
<p>We may publish statutory information about your licence application or changes to it for the public on our website.</p>

<h3>Data</h3>
<p>If you take any data from the service, you must keep it secure and destroy it when you’ve finished using it.</p>
<p>Unauthorised access to data’s illegal and may be an offence under the Computer Misuse Act 1990. It can lead to prosecution and/or claims for damages.</p>

<h3>Use of your credit/debit card details</h3>
<p>We can’t accept liability if your payment’s refused or declined by the card supplier.</p>
<p>It’s your responsibility to make sure payments are made on time.</p>
<p>We reserve the right to take legal action against people who commit or try to commit online frauds.</p>

<h3>Hyperlinking</h3>
<p><a href="https://www.gov.uk/help/terms-conditions">See the GOV.UK terms and conditions</a></p>

<h3>Keeping information up to date and updating our licence</h3>
<p>Under the Data Protection Act 1998 you can ask us to:</p>
<ul>
    <li>send a copy of personal information we hold about you</li>
    <li>correct any inaccuracies</li>
</ul>
<p>To request a copy or make changes email <a href="mailto:operatorlicensing@otc.gov.uk">operatorlicensing@otc.gov.uk</a>. We charge £10 for this service.</p>

<h3>Accurate and truthful information</h3>
<p>It’s your responsibility to make sure details submitted by you, or any of your organisation’s employees or agents, are accurate and truthful.</p>

<h3>Add or remove partners, directors or Transport Managers</h3>
<p>You should only remove a partner, director or Transport Manager if they’re no longer associated with the licence.</p>

<h3>Liability</h3>
<p>You aren’t liable for online transactions on your licences that aren’t carried out by you, or for access to or use of the service by someone else, unless:</p>
<ul>
    <li>you authorised the transaction, access to or use of the service</li>
    <li>you acted fraudulently or negligently, which includes not protecting your password</li>
</ul>
<p>We expect you to co-operate with the police if there’s an investigation. We’ll give the police any information that we think is relevant.</p>

<h3>Freedom of information</h3>
<p>We’re subject to the Freedom of Information Act 2000 and may have to reveal information about the service if there’s a request.</p>
<p>If we ask you to, you must help us comply with information disclosure requests that relate to online services or your licence.</p>

<h3>Waiver and enforceability</h3>
<p><a href="https://www.gov.uk/help/terms-conditions">See the GOV.UK terms and conditions</a></p>

<h3>Applicable law</h3>
<p><a href="https://www.gov.uk/help/terms-conditions">See the GOV.UK terms and conditions</a></p>

<h3>Variation</h3>
<p>We have the right to change these terms. If we make significant changes to them we’ll let you know.</p>
<p>New terms are effective once they’ve been posted on the site. If you use the site after they’ve been posted, you’re agreeing to them.</p>

<h3>Assignment</h3>
<p>Without written permission from us, you can’t assign, novate, sub-contract or dispose of or deal with your rights or obligations under these terms, or any part of them.</p>

<h3>Rights of third parties</h3>
<p>The rights in these terms can’t be enforced by anyone other than you and us.</p>

<h3>Entire agreement</h3>
<p>These terms of use constitute the entire understanding between the parties relating to the subject matter hereof and save as may be expressly referred to or referenced herein supersedes all prior representations, writings, negotiations or understandings with respect hereto, each party agreeing that it has not relied on any representation in entering into these terms of use.</p>
<p>Nothing in this clause shall however operate to limit or exclude liability for fraud.</p>