<div class="info-box info-box--grey">
    <h3 class="info-box__heading">Rhagor o wybodaeth</h3>
    
    <ul class="links-list">
        <li class="links-list__item">
            <a href="<?php echo $this->translate('being-an-operator-link'); ?>" target="_blank">
                <?php echo $this->translate('sidebar-variation-being-an-operator'); ?>
            </a>
        </li>
        <li class="links-list__item">
            <a href="<?php echo $this->translate('public-services-link'); ?>" target="_blank">
                <?php echo $this->translate('sidebar-variation-public-service'); ?>
            </a>
        </li>
        <li class="links-list__item">
            <a href="<?php echo $this->url('guides/guide', ['guide' => 'financial-evidence']); ?>">
                <?php echo $this->translate('sidebar-variation-financial-evidence'); ?>
            </a>
        </li>
        <li class="links-list__item">
            <a href="<?php echo $this->translate('vehicle-safety-link'); ?>" target="_blank">
                <?php echo $this->translate('sidebar-variation-safety-and-maintenance'); ?>
            </a>
        </li>
    </ul>
    
</div><!-- links -->