<h3><abbv title="European Conference of Ministers of Transport">CY - ECMT</abbv> permit </h3>
<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">CY - Help with ECMT permits</summary>
        <div class="article guidance">
            <p>CY - If you want to transport goods internationally, you can apply for an European Conference of Ministers of Transport (ECMT) permit.</p>
            <p>CY - Further <a href="<?php echo $this->translate('permits.link.ecmt.guidance'); ?>" target="_blank">guidance on ECMT permits</a> is available on GOV.UK.</p>
        </div>
    </details>
</div>
