<h2 class="govuk-heading-m govuk-!-margin-top-7" style="font-size: 24px !important">Cwcis sy'n mesur defnydd gwefan</h2>

<h3 class="govuk-heading-s" id="messages-across-govuk">Google analytics</h3>
<p>Rydym yn defnyddio meddalwedd Google Analytics (Universal Analytics) i gasglu gwybodaeth ddienw am sut rydych yn defnyddio'r safle hwn. Rydym yn gwneud hyn i helpu i sicrhau bod y safle yn diwallu anghenion ei ddefnyddwyr ac i'n helpu i wneud gwelliannau i'r safle ac i wasanaethau digidol y Llywodraeth.</p>

<div role="note" aria-label="Information" class="application-notice info-notice guidance">
    <p>Nid ydym yn caniatáu i Google ddefnyddio neu rannu'r data am sut rydych yn defnyddio'r safle hwn.</p>
</div>

<p>Mae Google Analytics yn storio gwybodaeth am:</p>

<ul class="govuk-list govuk-list--bullet">
    <li>sut y cawsoch chi'r safle</li>
    <li>y tudalennau rydych yn ymweld â nhw o fewn y gwasanaeth a faint o amser rydych yn ei dreulio arnynt</li>
    <li>Beth rydych chi'n clicio arno wrth ddefnyddio'r gwasanaeth</li>
</ul>

<p>Mae Google Analytics yn gosod y cwcis canlynol.</p>

<table style="font-size: 16px;">
    <thead>
    <tr>
        <th scope="col">Enw</th>
        <th scope="col">Diben</th>
        <th scope="col">Daw i ben</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>_ga</td>
        <td>Defnyddio i gyfrif faint o bobl sy'n ymweld â'r gwasanaeth trwy olrhain os ydych wedi ymweld cyn</td>
        <td>2 flynedd</td>
    </tr>
    <tr>
        <td>_gid</td>
        <td>Defnyddio i neilltuoli'n unigryw ymwelwyr â'r safle</td>
        <td>24 awr</td>
    </tr>
    <tr>
        <td>_gat</td>
        <td>Defnyddio i gyfyngu'r ceisiadau i Google</td>
        <td>1 funud</td>
    </tr>
    <tr>
        <td>__utmt</td>
        <td>Defnyddio i gyfyngu'r ceisiadau i Google</td>
        <td>10 munad</td>
    </tr>
    <tr>
        <td>_gat_{ID} </td>
        <td>Defnyddio i gyfyngu'r ceisiadau i Google</td>
        <td>1 funud</td>
    </tr>
    </tbody>
</table>
