<p class="govuk-body">Rydym wedi tynnu eich cais yn ôl ac ni fyddwch yn gallu ei weld na'i ddiweddaru mwyach.</p>
<p class="govuk-body">Os ydych chi'n dal i fod eisiau cludo nwyddau yn rhyngwladol bydd angen i chi wneud cais a defnyddio
    <a href="<?php echo $this->translate('permits.link.ecmt.guidance'); ?>" target="_blank">Trwydded Cludiant Ffyrdd Rhyngwladol<span class="govuk-visually-hidden">(dolen yn agor mewn ffenestr newydd)</span></a>.
</p>
