<h2 class="govuk-heading-m govuk-!-margin-top-7" style="font-size: 24px !important">Cwcis cwbl angenrheidiol</h2>
<p>Pan fyddwch yn defnyddio'r gwasanaeth 'gwneud cais am drwydded', byddwn yn gosod cwci i gofio eich cynnydd twy'r ffurflenni. Nid yw'r cwcis hyn yn storio eich data personol a chânt eu dileu ar ôl i chi gwblhau'r trafodyn.</p>

<table style="font-size: 16px;">
    <thead>
    <tr>
        <th>Enw</th>
        <th>Diben</th>
        <th>Daw i ben</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>PHPSESSID</td>
        <td>Storio gwybodaeth dros dro rhwng tudalennau i gyflymu eich pori</td>
        <td>Pan fyddwch yn cau eich porwr</td>
    </tr>
    <tr>
        <td>secureToken</td>
        <td>Storio gwybodaeth sylfaenol am eich manylion mewngofnodi</td>
        <td>Pan fyddwch yn cau eich porwr</td>
    </tr>
    <tr>
        <td>cookies_policy</td>
        <td>Cadw eich gosodiadau caniatâd cwcis</td>
        <td>1 flwyddyn</td>
    </tr>
    </tbody>
</table>
