<div class="govuk-box-highlight">
    <h1 class="js-title">%s</h1>
    <p>
        CY - You have removed your  <br>
        CY - ECMT permits application number   <br>
        <strong class="heading-medium">%s</strong>
    </p>
</div>
<div class="actions-container">
    <h3 class="heading-small">CY - What happens next</h3>
    <?php echo $this->partial('cy_GB/bullets/markup-ecmt-decline-submitted'); ?>
    <br />
    <div class="notice form-group">
        <p>CY - You can still apply for future ECMT Road Haulage permits but will need to start a new application.
            CY - Future application window periods for ECMT permits will be advertised on
            <a href="<?php echo $this->translate('permits.link.ecmt.guidance'); ?>" target="_blank">CY - Guidance on using ECMT</a>
        </p>
    </div>
</div>
