<h3>Diogelu data</h3>
<p>Bydd y comisiynydd traffig neu adran seilwaith Gogledd Iwerddon yn defnyddio'ch gwybodaeth bersonol fel rhan o'u
    gwaith.</p>
<p>Efallai y byddant yn ei rhannu â ' i gilydd ac:</p>

<ul>
    <li> comisiynwyr traffig eraill</li>
    <li> 'r adran drafnidiaeth</li>
    <li> adrannau eraill y Llywodraeth</li>
    <li> asiantaethau gorfodi</li>
</ul>

<p> efallai y byddwn hefyd yn ei ddefnyddio i gysylltu â chi ynglŷn ag ymchwil defnyddwyr. </p>
<p> Os ydych yn gwneud cais am drwydded safonol, mae ' n ofynnol i ni yn ôl y gyfraith i ychwanegu eich manylion at
    gofrestr genedlaethol. </p>

<p> byddwn yn rhannu data dienw gyda Gov.uk ar sut y gwnaethoch chi ddefnyddio'r safle. </p>

<h3>Cwcis</h3>
<p> Mae ein gwefan yn rhoi ffeiliau bach o'r enw Cwcis ar eich cyfrifiadur. </p>
<p> cwcis yn casglu gwybodaeth am sut rydych chi'n pori'r safle. Fel cyfeiriadau IP, ni ellir eu defnyddio i ' ch
    adnabod chi ' bersonol. </p>
<p> cwcis yn ein helpu: </p>
<ul>
    <li> mesurwch sut rydych yn defnyddio ' r safle er mwyn i ni ei ddiweddaru a ' i wella</li>
    <li> Cofiwch hysbysiadau rydych wedi ' u gweld fel nad ydym yn eu dangos i chi eto</li>
</ul>

<p> Dysgwch fwy am <a href="http://www.aboutcookies.org">sut i reoli cwcis </a></p>

<h4>Pa gwcis Rydym yn eu defnyddio?</h4>
<table>
    <tr>
        <th> Cwcis</th>
        <th> yr hyn y mae ' n ei wneud</th>
        <th> Yn dod i ben</th>
    </tr>
    <tr>
        <td> Google Analytics</td>
        <td> yn casglu gwybodaeth am sut rydych yn defnyddio ' r safle i wella ' r ffordd y mae ' r wefan hon yn
            gweithio. <a href="https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage">Darllen
                mwy am gwcis Google Analytics </a></td>
        <td> Gwel <a href="https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage">
                Canllaw Google ar ddefnyddio cwcis</a></td>
    </tr>
    <tr>
        <td> PHPSESSID</td>
        <td> yn storio gwybodaeth dros dro rhwng tudalennau i gyflymu eich pori</td>
        <td> pan fyddwch yn cau eich porwr</td>
    </tr>
    <tr>
        <td>secureToken</td>
        <td>yn storio gwybodaeth sylfaenol am eich manylion mewngofnodi</td>
        <td>
            pan fyddwch yn Caewch eich porwr
        </td>
    </tr>
    <tr>
        <td> cookie_seen</td>
        <td> yn rhoi gwybod i ni pa faneri a pop-ups yr ydych wedi ' u gweld felly dydyn ni ddim yn eu dangos i chi
            eto
        </td>
        <td> un mis</td>
    </tr>
    <tr>
        <td>langPref</td>
        <td>Yn dangos i ni p'un a ydych chi'n darllen yn Saesneg neu'n Gymraeg</td>
        <td> pan fyddwch yn clirio cwcis o'ch porwr</td>
    </tr>
    <tr>
        <td> incap_ses_ {ID}</td>
        <td> storfeydd dynodwyr a ddefnyddir gan ein gwasanaeth diogelwch gwefan i ddiogelu a gwella argaeledd ein
            safle
        </td>
        <td> pan fyddwch yn cau eich porwr</td>
    </tr>
    <tr>
        <td> nlbi_ {ID}</td>
        <td> storfeydd dynodwyr a ddefnyddir gan ein gwasanaeth diogelwch gwefan i ddiogelu a gwella argaeledd ein
            safle
        </td>
        <td> pan fyddwch yn cau eich porwr</td>
    </tr>
    <tr>
        <td> visid_incap_ {ID}</td>
        <td> storiau sesiwn dynodwyr a ddefnyddir gan ein gwasanaeth diogelwch gwefan i ddiogelu a gwella argaeledd ein
            safle
        </td>
        <td> un flwyddyn</td>
    </tr>
</table>
<h3>Cyfeiriadau IP</h3>
<p> Rydym yn defnyddio cyfeiriadau IP i: </p>
<ul>
    <li> monitro tueddiadau</li>
    <li> weld pa dudalennau y mae defnyddwyr yn ymweld â hwy</li>
    <li> dysgu sut mae gwahanol rannau o'r boblogaeth yn defnyddio'r safle</li>
</ul>
<p> allwn ni ddim defnyddio eich cyfeiriad IP i ' ch adnabod chi ' n bersonol. </p>

<h3>Gwasanaethau Llywodraeth</h3>
<p> Mae ' r rhan fwyaf o wasanaethau yr ydym yn cysylltu â hwy yn cael eu rhedeg gan wahanol
    adrannau Llywodraeth fel CThEM neu ' r Swyddfa Gartref. </p>
<p> gall y gwasanaethau hyn osod cwcis eraill a bydd
    ganddynt eu polisïau cwcis eu hunain.</p>