<p><b>Translated to Welsh</b></p>I confirm that:
<ul>
    <li>I am resident in the European Community;</li>
    <li>I shall perform my tasks solely in the interests of the licence holder/applicant;</li>
    <li>I shall be the Transport Manager for a maximum of 4 operators, with a combined maximum total fleet of 50 vehicles; and</li>
    <li>
        I have a contract with the licence holder/applicant which specifies the tasks I must perform as Transport Manager. These include:
        <?php // @todo Temp added until we have styles for nested uls ?>
        <ul style="margin-left: 40px; list-style: circle">
            <li>The making of arrangements to ensure that drivers comply with drivers’ hours and tachograph rules and with speed limits;</li>
            <li>The making of arrangements to ensure that the vehicles are maintained properly, including the inspection of vehicles at the appropriate time and the action taken to remedy defects found;</li>
            <li>The reporting and recording of vehicle defects by drivers;</li>
            <li>The method of compilation and the accuracy of all records, which must be kept for a period of not less than 15 months;</li>
            <li>The making of arrangements to ensure that the vehicle/s are not overloaded;</li>
            <li>Ensuring that authorised vehicles will be kept at the authorised operating centre(s) when not in use;</li>
            <li>Where appropriate, notifying the relevant traffic commissioner (in writing) of all prosecutions and convictions concerning the operator, the drivers and me within 28 days of the court hearing;</li>
            <li>Notifying the relevant traffic commissioner of my resignation; and</li>
            <li>
                Any role that I have in:
                <?php // @todo Temp added until we have styles for nested uls ?>
                <ul style="margin-left: 40px; list-style: square">
                    <li>Verifying contracts and documents;</li>
                    <li>Basic accounting;</li>
                    <li>Any other role in safety procedures.</li>
                </ul>
            </li>
        </ul>
    </li>
</ul>