<div class="actions-container article">
    <p class="extra-space">CY - By declining you accept that:</p>
    <ul class="list-bullet">
        <li>CY - Awarded permits will be cancelled permanently.</li>
        <li>CY - The information submitted will be deleted.</li>
        <li>CY - You’ll not be able to access your application again.</li>
        <li>CY - You’ll not receive a refund for the application fee paid.</li>
    </ul>
</div>