<p><b>Translated to Welsh</b></p>
  <div class="article">
    <h3 class="important">Important</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum blanditiis sed quo dolores omnis quam non deserunt iure voluptas ullam culpa in maxime, soluta architecto fugiat nemo eum hic ab.</p>
    <p>Sit amet, consectetur adipisicing elit. Veniam nisi expedita maiores illo quibusdam quis nemo, libero provident quaerat esse, autem doloremque, magnam perspiciatis, harum veritatis odit praesentium omnis iusto!</p>
  </div><!-- .article -->