<div class="links">
  <h3>Useful information for vehicle operators</h3>
  <ul class="links-list">
    <li class="links-list__item"><a href="">Complete your applications for a goods vehicle operator's licence</a></li>
    <li class="links-list__item"><a href="">Advertise your application for a licence</a></li>
    <li class="links-list__item"><a href="">Financial information</a></li>
    <li class="links-list__item"><a href="">A guide to operator fees</a></li>
    <li class="links-list__item"><a href="">How to draw up a maintenance contract</a></li>
  </ul>
</div><!-- links -->