<div class="gem-c-govspeak govuk-govspeak govuk-!-margin-top-7" data-module="govspeak">
    <h2 class="govuk-heading-m" style="font-size: 24px !important">Diogelu data</h2>
    <p>Bydd y Comisiynydd Trafnidiaeth neu Adran Isadeiledd Gogledd Iwerddon yn defnyddio'ch gwybodaeth bersonol fel rhan o'u gwaith. Efallai y byddant yn ei rhannu â'i gilydd a:</p>
    <ul class="govuk-list govuk-list--bullet">
        <li>Chomisiynwyr Trafnidiaeth eraill</li>
        <li>yr Adran Drafnidiaeth</li>
        <li>adrannau eraill y Llywodraeth</li>
        <li>asiantaethau gorfodis</li>
    </ul>
    <p>Efallai y byddwn hefyd yn ei ddefnyddio i gysylltu â chi ynghylch ymchwil defnyddwyr.</p>
    <p>Os ydych yn gwneud cais am drwydded safonol mae'n ofynnol yn gyfreithiol i ni ychwanegu eich manylion at gofrestr genedlaethol.</p>
    <p>Byddwn yn rhannu data dienw gyda GOV.UK ar sut y gwnaethoch chi ddefnyddio'r safle.</p>
</div>
