<div class="newspaper-advert info-box info-box--grey info-box--large-padding">
    <h3>Hysbyseb papur newyddion</h3>
    <p class="info-box__icon-wrapper info-box__text">
        <i class="info-box__icon selfserve-important"></i>
        Bydd angen ichi hysbysebu'r cais mewn papur newyddion lleol ac anfon copi i ni.
    </p>
    <p class="info-box__icon-wrapper info-box__text"><a href="%s" target="_blank">Gwelwch ein canllawiau ar sut i hysbysebu'ch cais</a><i class="icon selfserve-external-link"></i></p>
</div>
