<?php

/**
 * Section Access Test
 *
 * @author Rob Caiger <rob@clocal.co.uk>
 */
namespace CommonComponentTest\Lva;

use CommonTest\Bootstrap;
use PHPUnit_Framework_TestCase;
use Common\Service\Data\SectionConfig;
use Common\Service\Entity\LicenceEntityService;

/**
 * Section Access Test
 *
 * @author Rob Caiger <rob@clocal.co.uk>
 */
class SectionAccessTest extends PHPUnit_Framework_TestCase
{
    /**
     * @group component
     * @group lva_component
     * @group section_access_lva_component
     * @dataProvider providerSectionAccessExternalApplication
     */
    public function testSectionAccessExternalApplication($access, $expected)
    {
        $serviceManager = Bootstrap::getRealServiceManager();

        $mockVariationProcessor = $this->getMock('\stdClass', array('isNotUnchanged'));
        $mockVariationProcessor->expects($this->any())
            ->method('isNotUnchanged')
            ->willReturn(false);
        $serviceManager->setService('Processing\VariationSection', $mockVariationProcessor);

        $sectionConfig = new SectionConfig();
        $sectionConfig->setServiceLocator($serviceManager);
        $inputSections = $sectionConfig->getAll();

        $accessHelper = $serviceManager->get('Helper\Access');
        $accessibleSections = $accessHelper->setSections($inputSections)->getAccessibleSections($access);

        $this->assertEquals($expected, array_keys($accessibleSections));
    }

    public function providerSectionAccessExternalApplication()
    {
        return array(
            // EXTERNAL APPLICATION
            'External Application Goods Standard National' => array(
                array(
                    'external',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'transport_managers',
                    'vehicles',
                    'trailers',
                    'safety',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties',
                    'undertakings'
                )
            ),
            'External Application Goods Standard International' => array(
                array(
                    'external',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'transport_managers',
                    'vehicles',
                    'trailers',
                    'safety',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties',
                    'undertakings'
                )
            ),
            'External Application Goods Restricted' => array(
                array(
                    'external',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'vehicles',
                    'trailers',
                    'safety',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties',
                    'undertakings'
                )
            ),
            'External Application PSV Standard National' => array(
                array(
                    'external',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'transport_managers',
                    'vehicles_psv',
                    'vehicles_declarations',
                    'safety',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties',
                    'undertakings'
                )
            ),
            'External Application PSV Standard International' => array(
                array(
                    'external',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'transport_managers',
                    'vehicles_psv',
                    'vehicles_declarations',
                    'safety',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties',
                    'undertakings'
                )
            ),
            'External Application PSV Restricted' => array(
                array(
                    'external',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'vehicles_psv',
                    'vehicles_declarations',
                    'safety',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties',
                    'undertakings'
                )
            ),
            'External Application PSV Special Restricted' => array(
                array(
                    'external',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_SPECIAL_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'taxi_phv',
                    'undertakings'
                )
            ),
            // INTERNAL APPLICATION
            'Internal Application Goods Standard National' => array(
                array(
                    'internal',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'transport_managers',
                    'vehicles',
                    'safety',
                    'conditions_undertakings',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties'
                )
            ),
            'Internal Application Goods Standard International' => array(
                array(
                    'internal',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'transport_managers',
                    'vehicles',
                    'community_licences',
                    'safety',
                    'conditions_undertakings',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties'
                )
            ),
            'Internal Application Goods Restricted' => array(
                array(
                    'internal',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'vehicles',
                    'safety',
                    'conditions_undertakings',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties'
                )
            ),
            'Internal Application PSV Standard National' => array(
                array(
                    'internal',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'transport_managers',
                    'vehicles_psv',
                    'vehicles_declarations',
                    'safety',
                    'conditions_undertakings',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties'
                )
            ),
            'Internal Application PSV Standard International' => array(
                array(
                    'internal',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'transport_managers',
                    'vehicles_psv',
                    'vehicles_declarations',
                    'community_licences',
                    'safety',
                    'conditions_undertakings',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties'
                )
            ),
            'Internal Application PSV Restricted' => array(
                array(
                    'internal',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'vehicles_psv',
                    'vehicles_declarations',
                    'community_licences',
                    'safety',
                    'conditions_undertakings',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties'
                )
            ),
           'Internal Application PSV Special Restricted' => array(
                array(
                    'internal',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_SPECIAL_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'taxi_phv'
                )
            ),
            // EXTERNAL LICENCE
            'External Licence Goods Standard National' => array(
                array(
                    'external',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles',
                    'trailers',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            'External Licence Goods Standard International' => array(
                array(
                    'external',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles',
                    'trailers',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            'External Licence Goods Restricted' => array(
                array(
                    'external',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'vehicles',
                    'trailers',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            'External Licence PSV Standard National' => array(
                array(
                    'external',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles_psv',
                    'discs',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            'External Licence PSV Standard International' => array(
                array(
                    'external',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles_psv',
                    'discs',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            'External Licence PSV Restricted' => array(
                array(
                    'external',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'vehicles_psv',
                    'discs',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            'External Licence PSV Special Restricted' => array(
                array(
                    'external',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_SPECIAL_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'taxi_phv'
                )
            ),
            // INTERNAL LICENCE
            'Internal Licence Goods Standard National' => array(
                array(
                    'internal',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles',
                    'trailers',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            'Internal Licence Goods Standard International' => array(
                array(
                    'internal',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles',
                    'trailers',
                    'community_licences',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            'Internal Licence Goods Restricted' => array(
                array(
                    'internal',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'vehicles',
                    'trailers',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            'Internal Licence PSV Standard National' => array(
                array(
                    'internal',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles_psv',
                    'discs',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            'Internal Licence PSV Standard International' => array(
                array(
                    'internal',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles_psv',
                    'discs',
                    'community_licences',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            'Internal Licence PSV Restricted' => array(
                array(
                    'internal',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'vehicles_psv',
                    'discs',
                    'community_licences',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            'Internal Licence PSV Special Restricted' => array(
                array(
                    'internal',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_SPECIAL_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'taxi_phv'
                )
            ),
            // EXTERNAL VARIATION
            'External Variation Goods Standard National' => array(
                array(
                    'external',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles',
                    'trailers',
                    'safety',
                    'conditions_undertakings',
                    'undertakings'
                )
            ),
            'External Variation Goods Standard International' => array(
                array(
                    'external',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles',
                    'trailers',
                    'safety',
                    'conditions_undertakings',
                    'undertakings'
                )
            ),
            'External Variation Goods Restricted' => array(
                array(
                    'external',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'vehicles',
                    'trailers',
                    'safety',
                    'conditions_undertakings',
                    'undertakings'
                )
            ),
            'External Variation PSV Standard National' => array(
                array(
                    'external',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles_psv',
                    'discs',
                    'safety',
                    'conditions_undertakings',
                    'undertakings'
                )
            ),
            'External Variation PSV Standard International' => array(
                array(
                    'external',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles_psv',
                    'discs',
                    'safety',
                    'conditions_undertakings',
                    'undertakings'
                )
            ),
            'External Variation PSV Restricted' => array(
                array(
                    'external',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'vehicles_psv',
                    'discs',
                    'safety',
                    'conditions_undertakings',
                    'undertakings'
                )
            ),
            // INTERNAL VARIATION
            'Internal Variation Goods Standard National' => array(
                array(
                    'internal',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            'Internal Variation Goods Standard International' => array(
                array(
                    'internal',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles',
                    'community_licences',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            'Internal Variation Goods Restricted' => array(
                array(
                    'internal',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'vehicles',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            'Internal Variation PSV Standard National' => array(
                array(
                    'internal',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles_psv',
                    'discs',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            'Internal Variation PSV Standard International' => array(
                array(
                    'internal',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles_psv',
                    'discs',
                    'community_licences',
                    'safety',
                    'conditions_undertakings',
                )
            ),
            'Internal Variation PSV Restricted' => array(
                array(
                    'internal',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_type',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'vehicles_psv',
                    'discs',
                    'community_licences',
                    'safety',
                    'conditions_undertakings'
                )
            )
        );
    }
}
