<?php // Form for making direct request to payment system outside ?>

<p>Please wait&hellip;</p>

<form id="payment" class="js-hidden" action="<?php echo $gateway ?>" method="get">
  <button type="submit" data-prevent-double-click="true" class="govuk-button js-submit" data-module="govuk-button">Proceed to payment</button>
  <?php foreach ($data as $key => $value): ?>
    <input type="hidden" name="<?php echo $key ?>" value="<?php echo $value ?>" />
  <?php endforeach; ?>
</form>

<script>document.getElementById("payment").submit();</script>
