<?php
echo $this->partial(
    'partials/page-header-simple',
    [
        'pageTitle' => $this->pageTitle(),
        'pageSubTitle' => $this->licNo
    ]
);
?>
<h2><?php echo $this->translate($this->totalMessage) . ' ' . $this->totalCount; ?></h2>
<a class="hide-print" href="javascript:window.print();">
    <?php echo $this->translate('continuations.section.print.link'); ?>
</a>
<a href="javascript:window.close();">
    <?php echo $this->translate('continuations.section.close-the-window.link'); ?>
</a>
<div class="row">

  <div class="dashboard two-thirds js-body">
      <?php echo $this->partial('partials/checklist-section', ['data' => $this->data]); ?>
  </div>

</div>