<div class="row">
  <div class="two-thirds">
      <h1><?php echo $this->translate('continuations.success.title'); ?></h1>
      <p><?php echo $this->translate('continuations.success.subtitle'); ?></p>
      <div class="confirmation">
          <p><?php echo $this->translate('continuation.success.confirmation.your-licence-number'); ?></p>
          <h2><?php echo $this->escapeHtml($licNo); ?></h2>
          <?php if ($paymentRef): ?>
              <p>
                  <a
                      href="<?php echo $this->url('fees/receipt', ['action' => 'print', 'reference' => $paymentRef]);?>"
                      target="blank">
                      <?php echo $this->translate('continuation.success.confirmation.view-print-receipt'); ?>
                  </a>
              </p>
          <?php endif; ?>
      </div>
      <?php if (!$isDigital || $isFinancialEvidenceRequired): ?>
          <h2><?php echo $this->translate('continuation.success.confirmation.what-you-need-to-do'); ?></h2>
          <?php if (!$isDigital): ?>
              <div class="incomplete-section">
                  <h3><?php echo $this->translate('print-sign-return-declaration-form'); ?></h3>
                  <p>
                      <?php
                        echo $this->translate('continuation.success.declaration-send-text' . ($isNi ? '-ni' : ''));
                      ?>
                  </p>
                  <p>
                      <?php // @todo change route after merging develop into ?>
                      <a href="<?php echo $this->url('continuation/declaration', [], [], true); ?>" target="_blank">
                          <?php echo $this->translate('continuation.success.download-declaration-letter'); ?>
                      </a>
                  </p>
              </div>
          <?php endif; ?>
          <?php if ($isFinancialEvidenceRequired): ?>
              <div class="incomplete-section">
                  <h3><?php echo $this->translate('continuation.success.add-supporting-evidence'); ?></h3>
                  <p>
                      <?php
                        echo sprintf(
                            $this->translate('continuation.success.supporting-evidence-text' . ($isNi ? '-ni' : '')),
                                $this->url('guides/guide', ['guide' => 'financial-evidence'])
                        );
                      ?>
                  </p>
              </div>
          <?php endif; ?>
      <?php endif; ?>
      <h2><?php echo $this->translate('continuation.success.what-happens-next'); ?></h2>
      <div class="field">
        <p><?php echo $this->translate('continuation.success.licence-documentation'); ?></p>
      </div>
      <a href="<?php echo $this->url('lva-licence', ['licence' => $licenceId]) ?>" class="action--primary large">
          <?php echo $this->translate('continuation.success.finish'); ?>
      </a>
  </div>

</div>
