<?php
echo $this->partial(
    'partials/page-header-simple',
    [
        'pageTitle' => $this->pageTitle(),
        'pageSubTitle' => $this->translate('Continue licence') .' '. $this->licNo,
        'backUrl' => ['url' => $this->url('dashboard', [], [], true)],
    ]
);
?>

<div class="row">

  <div class="dashboard two-thirds js-body">
      <?php
      echo $this->flashMessengerAll();

      echo $this->partial('partials/guidance');

      if (isset($this->form)):
          echo $this->formErrors($this->form);
          echo $this->form($this->form);
      endif;
      ?>
  </div>

</div>