<ul class="govuk-list govuk-list--bullet">
    <li>I have read the <a href="<?php echo $this->translate('permits.link.ecmt.guidance') ?>">Guidance Notes</a> on how to use ECMT permits.</li>
    <li>I understand if a permit is issued it may exclude travel to Austria, Greece, Hungary, Italy and Russia as there are limited numbers of permits for travel to these countries.</li>
    <li>I understand that if a permit is issued I will be issued with a corresponding logbook which I must complete with full journey details before the start of a journey.</li>
    <li>I understand that I must carry a permit and corresponding logbook for the entire outbound and return journey.</li>
</ul>
