<ul class="list-bullet">
  <li>CY - I have read the <a href=<?php echo $this->translate('permits.link.ecmt.guidance') ?>>Guidance Notes</a> concerning ECMT permits.</li>

  <li>CY - I understand if a permit is issued it may include restrictions to Austria, Greece, Hungary, Italy and Russia.</li>

  <li>CY - You must carry and complete the correct matching logbook and permit for the entire outbound and return journey.</li>
</ul>
