<ul class="govuk-list govuk-list--bullet">
    <li>CY - You will receive a confirmation email in the next few minutes that we have received your application.</li>
    <li>CY - Your permit application will now be processed. We will contact you by email shortly after the application period has closed to tell you the outcome of your application.</li>
    <li>CY - You can check your application status on the next page.</li>
</ul>
