<p>Hauliers visiting Norway between 1 January 2021 and 30 September 2021 will only require permits if carrying out cabotage (transporting goods between 2 points within Norway).</p>
<p>Hauliers visiting Norway from 1 October 2021 onwards will require a standard permit to enter the country and a cabotage permit in addition if you wish to carry out cabotage.</p>
<p>Permits of all types are valid from the year they issued until 31 January the following year.</p>
<p>Applications can be made for either multi journey permits which allow unlimited journeys for the period the permit is valid or for single journey permits. Which types of permit are best for you depends on the number of journeys you are to take.</p>
