<h2 class="govuk-heading-m govuk-!-margin-top-7" style="font-size: 24px !important">Cookies that measure website use</h2>

<h3 class="govuk-heading-s" id="messages-across-govuk">Google analytics</h3>
<p>We use Google Analytics software (Universal Analytics) to collect anonymised information about how you use this site. We do this to help make sure the site is meeting the needs of its users and to help us make improvements to the site and to government digital services.</p>

<div role="note" aria-label="Information" class="application-notice info-notice guidance">
    <p>We do not allow Google to use or share the data about how you use this site.</p>
</div>

<p>Google Analytics stores information about:</p>

<ul class="govuk-list govuk-list--bullet">
    <li>how you got to the site</li>
    <li>the pages you visit within the service and how long you spend on them</li>
    <li>what you click on while using the service</li>
</ul>

<p>Google Analytics sets the following cookies.</p>

<table style="font-size: 16px;">
    <thead>
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Purpose</th>
        <th scope="col">Expires</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>_ga</td>
        <td>Used to count how many people visit the service by tracking if you’ve visited before</td>
        <td>2 years</td>
    </tr>
    <tr>
        <td>_gid</td>
        <td>Used to anonymously identify a user</td>
        <td>24 hours</td>
    </tr>
    <tr>
        <td>_gat</td>
        <td>Used to limit the requests to Google</td>
        <td>1 minute</td>
    </tr>
    <tr>
        <td>__utmt</td>
        <td>Used to limit the requests to Google</td>
        <td>10 minutes</td>
    </tr>
    <tr>
        <td>_gat_{ID} </td>
        <td>Used to limit the requests to Google</td>
        <td>1 minute</td>
    </tr>
    </tbody>
</table>
