<h3>Additional information (optional)</h3>

<p>You can upload more details about your vehicle safety and maintenance arrangements below. You do not need to provide your maintenance contract(s). See <a href="https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/321988/guide-to-maintaining-roadworthiness.pdf" target="_blank" rel="external">the safe operator’s guide</a> for more information.</p>

<details class="help">
    <summary class="help__summary" role="button" aria-expanded="false"> Examples of additional information</summary>
    <div class="article help__text">
        <ul>
            <li>Compliance reports</li>
            <li>Risk assessments</li>
            <li>Safety inspection records</li>
            <li>What systems you have in place for reporting defects</li>
            <li>What facilities you have for undertaking safety inspections (if relevant)</li>
        </ul>
    </div>
</details>