Read more about
<span id="typeOfLicence-hint-goods">
    <a 
        href="https://www.gov.uk/being-a-goods-vehicle-operator/types-of-licence"
        target="_blank" 
        aria-label="Read more about types of licence"
    >
        types of <span class="js-hidden"> goods vehicle </span>licence
    </a>
</span>
<span class="js-hidden"> or </span>
<span id="typeOfLicence-hint-psv">
    <a 
        href="https://www.gov.uk/psv-operator-licences"
        target="_blank" 
        aria-label="Read more about types of licence"
    >
        types of <span class="js-hidden"> public service vehicle </span> licence
    </a>
</span>
.
