<p class="govuk-body">You will receive an email to confirm that we have received your application.</p>
<p class="govuk-body">Your permit application is under consideration and will now be processed. We may contact you to verify your application. We will let you know the result of your application within 10 working days.</p>
<p class="govuk-body">You can check your application status on the next page.</p>
