<p class="govuk-body">We’ve withdrawn your application and you will no longer be able to view or update it.</p>
<p class="govuk-body">If you still wish to transport goods internationally you will need to apply and use an
    <a href="<?php echo $this->translate('permits.link.ecmt.guidance'); ?>" target="_blank">International Road Haulage Permit<span class="govuk-visually-hidden">(link opens in a new window)</span></a>.
</p>
