<p>Your details have been submitted.</p>

<p>You'll now need to:</p>

<ul>
    <li><b><a href="%s" target="_blank">print out your details</a></b></li>
    <li>sign them</li>
    <li>return them to the Central Licensing Office</li>
</ul>

<p>We'll let you know when we've received them.</p>

<p class="important"><strong><?php echo $this->translate('lva.section.title.transport-manager-application.important') ?></strong></p>
