<div class="article ecmt-countries">
    <div class="guidance-section">
        <h2>Where you can use ECMT permits</h2>
        <p>Road haulage operators can use ECMT permits to, from and between all 43 member countries and you will need ECMT permits when transporting to the following countries:</p>
    </div>
    <ul>
        <?php
        foreach ($ecmtCountries as $country) {
            echo "<li>" . $country . "</li>";
        }
        ?>
    </ul>
</div>
