<h2 class="govuk-heading-m govuk-!-margin-top-7" style="font-size: 24px !important">Strictly necessary cookies</h2>
<p>When you use the ‘apply for a licence’ service, we’ll set a cookie to remember your progress through the forms. These cookies do not store your personal data and are deleted once you’ve completed the transaction.</p>

<table style="font-size: 16px;">
    <thead>
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Purpose</th>
        <th scope="col">Expires</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>PHPSESSID</td>
        <td>Stores temporary information between pages to speed up your browsing</td>
        <td>When you close your browser</td>
    </tr>
    <tr>
        <td>secureToken</td>
        <td>Stores basic information about your login details</td>
        <td>When you close your browser</td>
    </tr>
    <tr>
        <td>cookies_policy</td>
        <td>Saves your cookie consent settings</td>
        <td>1 year</td>
    </tr>
    </tbody>
</table>
