<h3>Declaration information</h3>
<p>I have securely destroyed my vehicle discs and operator licence.</p>
<p>I will destroy any lost discs or licences that are found later.</p>
<p>I declare that the statement made in this application are true.</p>
<p>I am applying to surrender licence %s.</p>
<p>I understand that it is an offence to make a false declaration.</p>

<h3>Sign your declaration online</h3>
<p>You'll need to prove your identity with GOV.UK Verify or a digital identity from another European country</p>