<div class="article">
    <p>Great Britain is divided into 8 traffic areas. Each area has a Traffic Commissioner who’s responsible for issuing
        licences. Northern Ireland has a separate system.</p>
    <p>Your operating licence needs to be valid for the area(s) in which your operating centre(s) are based. If you have
        operating centres in more than one traffic area, you will need a separate licence for each area.</p>
    <h3>Which parts of the country do the traffic areas cover?</h3>
    <details class="govuk-details" data-module="govuk-details">
        <summary class="govuk-details__summary">
            <span class="govuk-details__summary-text">
                North Eastern
            </span>
        </summary>
        <div class="govuk-details__text">
            <h4>The metropolitan boroughs within:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>South Yorkshire</li>
                <li>Tyne and Wear</li>
                <li>West Yorkshire</li>
            </ul>
            <h4>The counties of:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>Durham</li>
                <li>Northumberland</li>
                <li>North Yorkshire</li>
                <li>Nottinghamshire</li>
            </ul>
            <h4>The districts of:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>Darlington</li>
                <li>East Riding of Yorkshire</li>
                <li>Hartlepool</li>
                <li>Kingston-upon-Hull</li>
                <li>Middlesbrough</li>
                <li>North East Lincolnshire</li>
                <li>North Lincolnshire</li>
                <li>Nottingham</li>
                <li>Redcar and Cleveland</li>
                <li>Stockton-on-Tees</li>
                <li>York</li>
            </ul>
            <h4>Contact details:</h4>
            <div>
                Hillcrest House<br/>
                Harehills Lane<br/>
                Leeds<br/>
                LS9 6NF
            </div>
        </div>
    </details>
    <details class="govuk-details" data-module="govuk-details">
        <summary class="govuk-details__summary">
            <span class="govuk-details__summary-text">
                North Western
            </span>
        </summary>
        <div class="govuk-details__text">
            <h4>The metropolitan boroughs within:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>Greater Manchester</li>
                <li>Merseyside</li>
            </ul>
            <h4>The counties of:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>Cheshire</li>
                <li>Cumbria</li>
                <li>Derbyshire</li>
                <li>Lancashire</li>
            </ul>
            <h4>The districts of:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>Blackburn with Darwen</li>
                <li>Blackpool</li>
                <li>Derby City</li>
                <li>Halton</li>
                <li>Warrington</li>
            </ul>
            <h4>Contact details:</h4>
            <div>
                Suit 4-6<br/>
                Stone Cross Place<br/>
                Stone Cross Lane<br/>
                Golborne<br/>
                Warrington<br/>
                WA3 2SH
            </div>
        </div>
    </details>
    <details class="govuk-details" data-module="govuk-details">
        <summary class="govuk-details__summary">
            <span class="govuk-details__summary-text">
                Eastern
            </span>
        </summary>
        <div class="govuk-details__text">
            <h4>The metropolitan boroughs within:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>Bedfordshire</li>
                <li>Buckinghamshire</li>
                <li>Cambridgeshire</li>
                <li>Essex</li>
                <li>Hertfordshire</li>
                <li>Leicestershire</li>
                <li>Lincolnshire (except the Districts of North Lincolnshire and North East Lincolnshire)</li>
                <li>Norfolk</li>
                <li>Northamptonshire</li>
                <li>Suffolk</li>
            </ul>
            <h4>The districts of:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>Leicester</li>
                <li>Luton</li>
                <li>Milton Keynes</li>
                <li>Peterborough</li>
                <li>Rutland</li>
                <li>Southend-on-Sea</li>
                <li>Thurrock</li>
            </ul>
            <h4>Contact details:</h4>
            <div>
                Eastbrook<br/>
                Shaftesbury Road<br/>
                Cambridge<br/>
                CB2 8BF
            </div>
        </div>
    </details>
    <details class="govuk-details" data-module="govuk-details">
        <summary class="govuk-details__summary">
            <span class="govuk-details__summary-text">
                Wales (Cymru)
            </span>
        </summary>
        <div class="govuk-details__text">
            <ul class="govuk-list govuk-list--bullet">
                <li>Wales (Cymru)</li>
            </ul>
            <h4>Contact details:</h4>
            <div>
                38 George Road<br/>
                Edgbaston<br/>
                Birmingham<br/>
                B15 1PL
            </div>
        </div>
    </details>
    <details class="govuk-details" data-module="govuk-details">
        <summary class="govuk-details__summary">
            <span class="govuk-details__summary-text">
                West Midlands
            </span>
        </summary>
        <div class="govuk-details__text">
            <h4>The counties of:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>Shropshire</li>
                <li>Staffordshire</li>
                <li>Warwickshire</li>
                <li>Worcestershire</li>
            </ul>
            <h4>The districts of:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>Herefordshire</li>
                <li>Stoke-on-Trent</li>
                <li>Telford and Wrekin</li>
            </ul>
            <h4>Contact details:</h4>
            <div>
                38 George Road<br/>
                Edgbaston<br/>
                Birmingham<br/>
                B15 1PL
            </div>
        </div>
    </details>
    <details class="govuk-details" data-module="govuk-details">
        <summary class="govuk-details__summary">
            <span class="govuk-details__summary-text">
                Western
            </span>
        </summary>
        <div class="govuk-details__text">
            <h4>The counties of:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>Cornwall</li>
                <li>Devon</li>
                <li>Dorset</li>
                <li>Gloucestershire</li>
                <li>Hampshire</li>
                <li>Oxfordshire</li>
                <li>Somerset</li>
                <li>Wiltshire</li>
            </ul>
            <h4>The districts of:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>Bath and North East Somerset</li>
                <li>Bournemouth</li>
                <li>Bracknell Forest</li>
                <li>Bristol</li>
                <li>Isle of Wight</li>
                <li>North Somerset</li>
                <li>Plymouth</li>
                <li>Poole</li>
                <li>Portsmouth</li>
                <li>Reading</li>
                <li>Slough</li>
                <li>Southampton</li>
                <li>South Gloucestershire</li>
                <li>Swindon</li>
                <li>Torbay</li>
                <li>West Berkshire</li>
                <li>Windsor and Maidenhead</li>
                <li>Workingham</li>
            </ul>
            <h4>Contact details:</h4>
            <div>
                Jubilee House<br/>
                Croydon Street<br/>
                Bristol<br/>
                BS5 0GB
            </div>
        </div>
    </details>
    <details class="govuk-details" data-module="govuk-details">
        <summary class="govuk-details__summary">
            <span class="govuk-details__summary-text">
                South Eastern and Metropolitan
            </span>
        </summary>
        <div class="govuk-details__text">
            <ul class="govuk-list govuk-list--bullet">
                <li>Greater London</li>
            </ul>
            <h4>The districts of:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>Kent</li>
                <li>Surrey</li>
                <li>East Sussex</li>
                <li>West Sussex</li>
            </ul>
            <h4>The districts of:</h4>
            <ul class="govuk-list govuk-list--bullet">
                <li>Brighton and Hove</li>
                <li>the Medway Towns</li>
            </ul>
            <h4>Contact details:</h4>
            <div>
                Ivy House<br/>
                3 Ivy Terrace<br/>
                Eastbourne<br/>
                BN21 4QT
            </div>
        </div>
    </details>
    <details class="govuk-details" data-module="govuk-details">
        <summary class="govuk-details__summary">
            <span class="govuk-details__summary-text">
                Scotland
            </span>
        </summary>
        <div class="govuk-details__text">
            <ul class="govuk-list govuk-list--bullet">
                <li>Scotland</li>
            </ul>
            <h4>Contact details:</h4>
            <div>
                Level 6<br/>
                The Stamp Office<br/>
                10 Waterloo Palace<br/>
                Edinburgh<br/>
                EH1 3EG
            </div>
        </div>
    </details>
</div>