<details class="govuk-details" data-module="govuk-details" role="group">
    <summary class="govuk-details__summary" role="button" aria-controls="details-content-0" aria-expanded="false">
        <span class="govuk-details__summary-text"><?php echo $this->translate('permits.page.bilateral.countries.essential.cabotage.heading'); ?></span>
    </summary>
    <div class="govuk-details__text" id="details-content-0" aria-hidden="true">
        <?php echo $this->translate('permits.page.bilateral.countries.essential.cabotage.desc'); ?>
    </div>
</details>
