<p class="govuk-body">
    This website is run by DVSA on behalf of the Traffic Commissioners for Great Britain, the Department for Infrastructure Northern Ireland and the International Road Haulage Permits.
</p>

<p class="govuk-body">
    We want as many people as possible to be able to use this website. For example, that means you should be able to:
</p>

<ul class="govuk-list govuk-list--bullet">
    <li>zoom in up to 300% without problems</li>
    <li>navigate most of the website using just a keyboard</li>
    <li>navigate most of the website using speech recognition software</li>
    <li>use most of the website using a screen reader (including the most recent versions of JAWS, NVDA and VoiceOver)</li>
</ul>

<h2 id="how-accessible-this-website-is" class="govuk-heading-l">How accessible this website is</h2>
<p class="govuk-body">
    Parts of this website are not fully accessible. For example, we use some custom controls which will be unfamiliar in the way they appear and operate.
</p>

<h2 id="feedback-and-contact-information" class="govuk-heading-l">Feedback and contact information</h2>
<p class="govuk-body">
    If you need information on this website in a different format, or you need assistance using this website call 0300 123 9000
</p>

<h3 id="contacting-us-by-phone-or-visiting-us-in-person" class="govuk-heading-m">Contacting us</h3>
<p class="govuk-body">
    <?php echo $this->linkNewWindowExternal('https://www.gov.uk/contact-dvsa', 'Find out how to contact DVSA'); ?>.
</p>

<h2 id="reporting-accessibility-problems-with-this-website" class="govuk-heading-m">Reporting accessibility problems with this website</h2>
<p class="govuk-body">
    If you find any problems not listed on this page or think we’re not meeting accessibility requirements, contact our dedicated accessibility team <?php echo $this->link('mailto:accessibility@vehicle-operator-licensing.service.gov.uk', 'accessibility@vehicle-operator-licensing.service.gov.uk'); ?> and tell us:
</p>
<ul class="govuk-list govuk-list--bullet">
    <li>the web address (URL) of the content</li>
    <li>the problem that you encountered</li>
</ul>

<h2 id="enforcement-procedure" class="govuk-heading-m">Enforcement procedure</h2>
<p class="govuk-body">
    The Equality and Human Rights Commission (EHRC) is responsible for enforcing the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018 (the ‘accessibility regulations’).
</p>
<p class="govuk-body">
If you contact us with a complaint and you’re not happy with our response  <?php echo $this->linkNewWindowExternal('https://www.equalityadvisoryservice.com/', 'contact the Equality Advisory and Support Service (EASS)'); ?>.
</p>
<p class="govuk-body">
    If you are an operator based in Northern Ireland, and you are not not happy with how we respond to your complaint, contact the <?php echo $this->linkNewWindowExternal('https://www.equalityni.org/Home', 'Equalities Commission for Northern Ireland (ECNI)'); ?>.
</p>

<h2 id="technical-information-about-this-websites-accessibility" class="govuk-heading-l">Technical information about this website’s accessibility</h2>
<p class="govuk-body">
    DVSA is committed to making its website accessible, in accordance with the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018.
</p>

<h2 id="compliance-status" class="govuk-heading-l">Compliance status</h2>
<p class="govuk-body">
    This website is partially compliant with the <?php echo $this->linkNewWindowExternal('https://www.w3.org/TR/WCAG21/', 'Web Content Accessibility Guidelines version 2.1'); ?> AA standard.
</p>

<h2 id="non-accessible-content" class="govuk-heading-l">Non-accessible content</h2>
<p class="govuk-body">
    The content listed below is non-accessible for the following reasons.
</p>

<h3 id="non-compliance-with-the-accessibility-regulations" class="govuk-heading-m">Non-compliance with the accessibility regulations</h3>
<p class="govuk-body">
    We have addressed all non-accessible content identified in our last accessibility audit. We will schedule another accessibility audit and update this section when any further issues have been identified.
</p>

<h3 id="disproportionate-burden" class="govuk-heading-m">Disproportionate burden</h3>
<p class="govuk-body">
    We intend to make our services compliant with the <?php echo $this->linkNewWindowExternal('https://www.w3.org/TR/WCAG21/', 'Web Content Accessibility Guidelines version 2.1'); ?> AA standard. We are not claiming disproportionate burden for any part of our accessibility plan.
</p>

<h3 id="content-thats-not-within-the-scope-of-the-accessibility-regulations" class="govuk-heading-m">
    Content that’s not within the scope of the accessibility regulations
</h3>
<p class="govuk-body">
    Non-HTML documents published before September 2018 do not need to be accessible - unless users need them to use a service.

</p>

<h2 id="how-we-tested-this-website" class="govuk-heading-l">
    How we tested this website
</h2>

<p class="govuk-body">
    We used this approach to decide a sample of pages to test:
</p>

<ul class="govuk-list govuk-list--bullet">
    <li>our highest volume transaction (vehicle changes)</li>
    <li>all sections of the ‘Manage my licence’ user journey (which duplicates the main pages of the ‘Apply for a licence’ journey</li>
    <li>journeys we know cause problems for users (change operating centre and vehicle authorisation, reviewing the submission)</li>
    <li>links to external pages containing further advice</li>
    <li>critical pages underpinning compliance (the document/correspondence section of the website)</li>
</ul>

<p class="govuk-body">
    Our public search pages and internal caseworker pages were tested internally using GDS guidance and insights from the independent accessibility audit conducted by DAC.
</p>

<p class="govuk-body">
    This website was last tested on 13 to 17 January 2020 by The Digital Accessibility Centre (DAC).
</p>

<h2 id="improve-accessibility-statement" class="govuk-heading-l">
    What we’re doing to improve accessibility</h2>

<p class="govuk-body">
    Following the audit conducted by the DAC in January 2020, we are urgently fixing content which fails to meet the Web Content Accessibility Guidelines version 2.1 AA standard.
</p>

<h2 id="preparation-of-this-accessibility-statement" class="govuk-heading-l">
    Preparation of this accessibility statement
</h2>
<p class="govuk-body">
    This statement was prepared on 10 August 2020. It was last reviewed on 19 May 2023.
</p>