<details>
    <summary class="help__summary">
        What's a traffic area?
    </summary>
    <div class="help__text">
        <p>Great Britain is divided into eight traffic areas. Each area has a Traffic Commissioner, who’s responsible for issuing licences.</p>
        <p>Traffic areas are determined by where your operating centres are.</p>
        <p>You need separate licences if your operating centres are in different traffic areas.</p>
    </div>
</details>
