<h3><?php echo $this->translate('lva-tm-details-details-certificateHtml-header'); ?></h3>
<p class="govuk-body"><?php echo $this->translate('lva-tm-details-details-certificateHtml-text'); ?></p>
<ul class="govuk-list govuk-list--bullet">
    <li><?php echo $this->translate('lva-tm-details-details-certificateHtml-bullet1'); ?></li>
    <li><?php echo $this->translate('lva-tm-details-details-certificateHtml-bullet2'); ?></li>
</ul>