<details class="govuk-details" data-module="govuk-details">
    <summary class="govuk-details__summary">
        <span class="govuk-details__summary-text"><?php echo $this->translate('permits.page.bilateral.countries.essential.cabotage.heading'); ?></span>
    </summary>
    <div class="govuk-details__text">
        <?php echo $this->translate('permits.page.bilateral.countries.essential.cabotage.desc'); ?>
    </div>
</details>
