<div class="gem-c-govspeak govuk-govspeak govuk-!-margin-top-7" data-module="govspeak">
    <h2 class="govuk-heading-m" style="font-size: 24px !important">Data protection</h2>
    <p>The Traffic Commissioner or Department for Infrastructure Northern Ireland will use your personal information as part of their work. They may share it with each other and:</p>
    <ul class="govuk-list govuk-list--bullet">
        <li>other Traffic Commissioners</li>
        <li>the Department for Transport</li>
        <li>other government departments</li>
        <li>enforcement agencies</li>
    </ul>
    <p>We may also use it to contact you about user research.</p>
    <p>If you apply for a standard licence we’re legally required to add your details to a national register.</p>
    <p>We will share anonymised data with GOV.UK on how you used the site.</p>
</div>
