<div class="gem-c-contextual-footer govuk-!-margin-top-8">
    <div class="gem-c-related-navigation">
        <nav role="navigation" class="gem-c-related-navigation__nav-section" aria-labelledby="related-nav-related_external_links-cac8d856" data-module="gem-toggle">
            <h2 id="related-nav-related_external_links-cac8d856" class="govuk-heading-m gem-c-related-navigation__sub-heading gem-c-related-navigation__sub-heading--footer  gem-c-related-navigation__sub-heading--other" data-track-count="footerRelatedItemSection">Elsewhere on the web</h2>
            <ul class="govuk-list gem-c-related-navigation__link-list" data-module="track-click">
                <li class="gem-c-related-navigation__link"><a class="gem-c-related-navigation__section-link gem-c-related-navigation__section-link--footer  gem-c-related-navigation__section-link--other" rel="external noreferrer noopener" data-track-category="relatedLinkClicked" data-track-action="1.1 Elsewhere on the web" data-track-label="{{URL_INFORMATION_COMMISSIONER_COOKIE}}" data-track-options="{&quot;dimension28&quot;:&quot;1&quot;,&quot;dimension29&quot;:&quot;Information Commissioner's Office: cookies&quot;}" href="{{URL_INFORMATION_COMMISSIONER_COOKIE}}" target="_blank">Information Commissioner's Office: cookies <?php echo $this->escapeHtml($this->translate('link.opens-new-window')); ?></a></li>
            </ul>
        </nav>
    </div>
</div>
