<?php
    $businessDetailsData = [];
    if (isset($this->businessDetails['companyNumber'])) {
        $businessDetailsData[] = [
            ['value' => $this->translate('continuations.business-details.company-number'), 'header' => true],
            ['value' => $this->businessDetails['companyNumber']]
        ];
    }
    if (isset($this->businessDetails['companyName'])) {
        $businessDetailsData[] = [
            ['value' => $this->businessDetails['organisationLabel'], 'header' => true],
            ['value' => $this->businessDetails['companyName']]
        ];
    }
    if (isset($this->businessDetails['tradingNames'])) {
        $businessDetailsData[] = [
            ['value' => $this->translate('continuations.business-details.trading-names'), 'header' => true],
            ['value' => $this->businessDetails['tradingNames']]
        ];
    }
?>
<?php echo $this->partial('partials/checklist-section', ['data' => $businessDetailsData]); ?>
