<ul class="govuk-list govuk-list--bullet">
    <li>you have read the <a href="{{ECMT_PERMITS_GUIDANCE_LINK}}" target="_blank">guidance notes<span class="govuk-visually-hidden">(link opens in a new window)</span></a> on how to use Short-term ECMT permits.</li>
    <li>you will comply fully with the conditions of use under which the permits may be used.</li>
    <li>you understand that this permit is for transiting through EU member states to non-EU countries who are ECMT members, including Switzerland.</li>
    <li>you understand that this permit is for a third cross-trade trip within 7 days.</li>
    <li>you understand that Short-term permits are not valid for Austria.</li>
    <li>you will only use the appropriate Euro emission standard vehicle that the permit allows.</li>
    <li>you understand you must obtain a Certificate of Compliance and a Certificate of Roadworthiness for each vehicle and trailer you intend to use.</li>
    <li>your driver must carry the permit and corresponding logbook, and the certificates for the entire outbound and return journey and present it to any competent authority or inspectors.</li>
    <li>you understand that Short-term ECMT permits can only be used for 30 consecutive days during the calendar year they have been issued.</li>
    <li>you will complete the paper permit with the start and end dates before starting your journey.</li>
    <li>you understand the logbook must be returned to DVSA within 2 weeks after returning to the UK.</li>
</ul>
