<ul class="govuk-list govuk-list--bullet">
    <li>You have read the <a href="{{IRHP_REMOVAL_GUIDANCE_LINK}}" target="_blank">guidance notes<span class="govuk-visually-hidden">(link opens in a new window)</span></a> on how to use ECMT international removal permits.</li>
    <li>You will comply fully with the conditions of use under which the permits may be used.</li>
    <li>You understand you must obtain a Certificate of Compliance and a Certificate of Roadworthiness for each vehicle and trailer you intend to use.</li>
    <li>Your driver will carry the permit and the certificates for the entire outbound and return journey and present it to any competent authority or inspectors.</li>
    <li>Your company uses specialised equipment and staff to undertake removal operations.</li>
    <li>You understand that this permit can only be used for international removals between ECMT member countries.</li>
    <li>You understand that, when transiting, you can only use it to deliver removal goods and business possessions to other ECMT countries.</li>
</ul>
