<p>You've confirmed this Transport Manager’s details.</p>
<p>You’ll now need to:</p>
<ul>
    <li><b><a href="%s" target="_blank">print out their details</a></b></li>
    <li>co-sign them with the Transport Manager</li>
    <li>return them to the Central Licensing Office</li>
</ul>
<p>We’ll let you know when we’ve received their details.</p>

<h3 class="important">Important</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur voluptatum suscipit dolorem facere, id quae est! Possimus ipsa tempore libero!</p>