<h3>Submit online</h3>

<div class="verify">
    <p>
        Registering with GOV.UK VERIFY will allow you to submit your Transport Manager form online
    </p>

    <div class="actions-container">
        <a href="?register=tmsigned" class="action--verify">Register for verify</a> <a href="">I already have an account</a>
    </div>
</div>


<h3>Print, sign and post</h3>
<p>
    If you are unable to submit your form online then please follow these steps:
</p>

<ul class="steps">
    <li>
        <h4>1. Print out your completed form</h4>
        <p>Print the following form out:<br>
            <a href="%s" target="_blank">View form</a>
        </p>
        <p>
            Not right? <a href="%s" class="js-modal-ajax">Edit form</a>
        </p>
    </li>
    <li>
        <h4>2. Co-sign the form</h4>
        <p>
            Your details must be checked and co-signed by yourself and the Licenced Operator. If you are an Owner or Director, you may co-sign the form yourself.
        </p>
    </li>
    <li>
        <h4>3. Post the form</h4>
        <p>Post the co-signed application, including any supporting documents to:</p>
        <p><?php echo $this->partial('partials/office-address')?></p>
    </li>
</ul>

<h3 class="important">Important</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sagittis dictum tortor, nec ornare metus ultrices eget. Curabitur et consectetur nunc. Quisque ligula metus, ultrices eu urna sit amet, cursus egestas nulla. Suspendisse sodales facilisis massa vel consectetur. Maecenas viverra bibendum eros. Pellentesque pellentesque enim nec nisi varius rhoncus. Nam condimentum a dui non fermentum. Donec lobortis leo vitae urna bibendum auctor.</p>
