<?php
$peopleData[] = [
    ['value' => $this->translate('continuations.people-section.table.name'), 'header' => true],
    ['value' => $this->translate('continuations.people-section.table.date-of-birth'), 'header' => true],
];
$persons = $this->people['persons'];
if (is_array($persons) && count($persons) <= $this->people['displayPersonCount']) {
    foreach ($persons as $person) {
        $peopleData[] = [
            ['value' => $person['name']],
            ['value' => $person['birthDate']]
        ];
    }
}
?>
<?php echo $this->partial('partials/checklist-section', ['data' => $peopleData]); ?>
