<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">
            European Conference of Ministers of Transport (ECMT)
        </summary>
        <div class="article help__text">
            <p>European Conference of Ministers of Transport (EMCT) multilateral road haulage permits</p>
            <ul>
                <li>ECMT permits may be used for journeys between member countries, including transit journeys whether laden or empty.</li>
                <li>They can also be used for third-country journeys to other ECMT countries which would otherwise be prohibited under certain bilateral agreements.</li>
                <li>ECMT permits are valid for one calendar year and allow an unlimited number of journeys within that period. The UK does not issue short-term permits.</li>
                <li>Permits may be transferred between vehicles, but are valid for only one vehicle at a time. The permit must be kept on board for the whole journey.</li>
            </ul>
        </div>
    </details>
</div>
