<h3 class="govuk-heading-m">By signing the declaration you are confirming your status as an internal transport manager,
    an external transport
    manager, or both, and understand that your duties include:</h3>
<h4 class="govuk-heading-s">Drivers administration</h4>
<p class="govuk-body">
    Including the checking of drivers' licences and driver CPC qualifications (DQC), ensuring that the retention of
    drivers hours records (no less than 12 months) and working time records (no less than 24 months) and both are
    made available upon request.
</p>
<h4 class="govuk-heading-s">Drivers management</h4>
<p class="govuk-body">
    Ensuring compliance with the driving hours rules (EU or Domestic Hours rules); that drivers record their duty,
    driving time and rest breaks; to download and store digital tachograph unit data (at least every 90 days) and
    from the drivers’ smart cards (at least every 28 days); ensuring that the following records are retained -
    drivers’ hours, Working Time Directive (WTD), and that they are available to be produced during the relevant
    period; ensuring that drivers are adequately trained and competent to operate relevant vehicles and equipment.
</p>
<h4 class="govuk-heading-s">Drivers operations</h4>
<p class="govuk-body">
    Ensuring drivers are completing and returning their driver defect reporting sheets and that defects are recorded
    correctly and cross checked, and that drivers and mobile workers take adequate breaks and appropriate periods of
    daily and weekly rest.
</p>
<h4 class="govuk-heading-s">Vehicle administration</h4>
<p class="govuk-body">
    Including ensuring that vehicle maintenance records are retained for a period of no less than 15 months,
    ensuring that vehicles are specified as required and that operator licence discs are current and displayed
    correctly; ensuring safe loading with appropriate indicators fitted, that tachograph calibrations are up to date
    and displayed, that there are up to date insurance certificates; a suitable maintenance planner is complete and
    displayed with preventative maintenance inspection dates at least 6 months in advance, to include the Annual
    Test and other testing or calibration dates.
</p>
<h4 class="govuk-heading-s">Vehicle management</h4>
<p class="govuk-body">
    Ensuring that vehicles and trailers are kept in a fit and roadworthy condition, that defects are either recorded
    and repaired promptly and where not roadworthy are taken out of service; to make vehicles and towed equipment
    for safety inspections, service, repair and statutory testing available at the appropriate times and within the
    notified O-licence maintenance intervals; to liaise with maintenance contractors, manufacturers, hire companies
    as might be appropriate. Ensuring that vehicles and trailers are parked at the nominated operating centre(s)
    when not in use.
</p>
<h4 class="govuk-heading-s">Licence administration</h4>
<p class="govuk-body">
    Ensuring that the traffic commissioner is made aware of any relevant matters within 28 days including
    convictions and prosecutions of the transport manager(s) or drivers and also of my own resignation should I
    leave the employment of the operator.
</p>
<h3 class="govuk-heading-m">Internal transport manager’s declaration</h3>
<p class="govuk-body">I confirm that:</p>
<ul>
    <li>
        I shall effectively and continuously manage the transport activities of the licence holder/applicant;
    </li>
    <li>
        I have a genuine link to the licence holder/applicant; and
    </li>
    <li>
        I am resident in the European Community.
    </li>
</ul>

<h3 class="govuk-heading-m">External transport manager’s declaration</h3>
<p class="govuk-body">I confirm that:</p>
<ul>
    <li>
        I am resident in the European Community;
    </li>
    <li>
        I shall perform my tasks solely in the interests of the licence holder/applicant;
    </li>
    <li>
        I shall be the transport manager for a maximum of 4 operators, with a combined maximum total fleet of 50
        vehicles; and
    </li>
    <li>
        I have a contract with the licence holder/applicant which specifies the tasks I must perform as transport
        manager.
    </li>
</ul>
<p class="govuk-body govuk-!-font-weight-bold">
    Should I fail to meet any of the above requirements I understand that the traffic commissioner has the power to
    disqualify me from being a transport manager in any European Union country. I also understand that I do not become a
    CPC holder for the licence(s) named until this is confirmed in writing by the Traffic Commissioner.
</p>
<h3 class="govuk-heading-m">Declaration by the applicant for the licence, or the licence holder</h3>
<p class="govuk-body">
    I confirm that to the best of my knowledge and belief the details given in this form are correct and understand that
    the above named applicant does not become a CPC holder for the licence(s) named until this is confirmed in writing
    by the Traffic Commissioner.
</p>