<div class="hint space">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">Help calculating your international trips</summary>
        <div class="article guidance">
            <p>You need to tell us all return journeys that:</p>
            <br />
            <div>
                <b>start and finish inside the UK and go to or pass through any EU country and or Iceland, Liechtenstein plus Norway</b>
                <br />
                <br />
                <p class="hint">
                    For example: Your truck leaves the UK, drives through France, Germany and Poland to reach Ukraine and returns
                    via Hungary, Austria, Switzerland and France. This is counted as one international journey.
                </p>
                <hr class="fieldset add-another-group">
            <div>
            <div>
                <b>start and finish outside of the UK but inside any EU country, Iceland, Liechtenstein or Norway</b>
                <br />
                <br />
                <p class="hint">
                    For example: Your truck leaves the UK, drives through France, Belgium and Switzerland to reach Liechtenstein and returns
                    via Austria, Germany, Switzerland, Italy and France. This is also counted as one international journey.
                </p>
                <hr class="fieldset add-another-group">
            <div>
            <div>
                <b>start and finish outside any of the countries listed above but your journey passes through any these countries</b>
                <br />
                <br />
                <p class="hint">
                    Your truck drives to Ireland to pick up goods, drives through the UK and France to reach Spain
                    and returns through France to the UK. This is counted as one international journey.
                </p>
                <hr class="fieldset add-another-group">
            <div>
        </div>
    </details>
</div>
