<div class="links">
    
    <h3>More information</h3>
    
    <ul class="links-list">
        <li class="links-list__item">
            <a href="<?php echo $this->translate('being-an-operator-link'); ?>" target="blank">
                Being a goods vehicle operator
            </a>
        </li>
        <li class="links-list__item">
            <a href="<?php echo $this->translate('public-services-link'); ?>" target="blank">
                Public Service Vehicle operator licences
            </a>
        </li>
        <li class="links-list__item">
            <a href="<?php echo $this->url('guides/guide', ['guide' => 'advertising-your-operating-centre-gb']); ?>">
                How to advertise your goods application
            </a>
        </li>
        <li class="links-list__item">
            <a href="<?php echo $this->url('guides/guide', ['guide' => 'financial-evidence']); ?>">
                How to provide financial evidence
            </a>
        </li>
        <li class="links-list__item">
            <a href="<?php echo $this->translate('vehicle-safety-link'); ?>" target="blank">
                Vehicle safety and maintenance guides
            </a>
        </li>
    </ul>
    
</div><!-- links -->