<div class="actions-container article">
    <p class="extra-space">By declining you accept that:</p>
    <ul class="list-bullet">
        <li>Awarded permits will be cancelled permanently.</li>
        <li>The information submitted will be deleted.</li>
        <li>You’ll not be able to access your application again.</li>
        <li>You’ll not receive a refund for the application fee paid.</li>
    </ul>
</div>