<p>When applying for an operator’s licence you must tell us about all the relevant convictions and penalties relating to:</p>
<ul>
    <li>Directors, Partners and Transport Managers</li>
    <li>Companies that are (or have been) directed by anybody you’ve named</li>
    <li>your parent company, if you’re a limited company</li>
    <li>your employees and agents</li>
</ul>
<p>You should provide full details of the background circumstances of any convictions or penalties declared and it’s a <span style="font-weight: bold;">criminal offence to make a false declaration.</span></p>

<h3>Spent Convictions</h3>
<p>You don’t have to disclose convictions spent under the Rehabilitation of Offenders Act 1974. The table below shows the period, after which convictions don’t need to be disclosed. The rehabilitation period depends on the sentence for the original offence and runs from the date of conviction. The Legal Aid, Sentencing and Punishment of Offenders Act 2012 amends the rehabilitation period as follows:</p>

<h3>Custodial sentences involving adult offenders</h3>
<p>
<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">
            MORE THAN 30 MONTHS up to, or consisting of 48 MONTHS
        </summary>
        <div class="article help__text">
            The end of the period of 7 years beginning with the day on which the sentence (including any licence period) is completed. Sentences above 48 months are excluded from rehabilitation.
        </div>
    </details>
</div>
<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">
            MORE THAN 6 MONTHS up to, or consisting of 30 MONTHS
        </summary>
        <div class="article help__text">
            The end of the period of 48 months beginning with the day on which the sentence (including any licence period) is completed.
        </div>
    </details>
</div>
<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">
            6 MONTHS or less
        </summary>
        <div class="article help__text">
            The end of the period of 48 months beginning with the day on which the sentence (including any licence period) is completed.
        </div>
    </details>
</div>

<h3 style="margin-top: 20px">Non-custodial sentences involving adult offenders</h3>
<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">
            Community or youth rehabilitation order
        </summary>
        <div class="article help__text">
            The end of 12 months beginning with the day provided for by or under the order as the last day on which the order is to have effect.
        </div>
    </details>
</div>
<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">
            Fine
        </summary>
        <div class="article help__text">
            The end of 12 months beginning with the date of the relevant conviction
        </div>
    </details>
</div>
</p>

<h3 style="margin-top: 20px">Custodial sentences involving offenders under 18</h3>
<p>
<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">
            MORE THAN 30 MONTHS up to, or consisting of 48 MONTHS
        </summary>
        <div class="article help__text">
            Up to 48 months - The end of the period of 42 months beginning with the day on which the sentence (including any licence period) is completed.
        </div>
    </details>
</div>
<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">
            MORE THAN 6 MONTHS up to, or consisting of 30 MONTHS
        </summary>
        <div class="article help__text">
            The end of the period of 24 months beginning with the day on which the sentence (including any licence period) is completed.
        </div>
    </details>
</div>
<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">
            6 MONTHS or less
        </summary>
        <div class="article help__text">
            The end of the period of 24 months beginning with the day on which the sentence (including any licence period) is completed.
        </div>
    </details>
</div>
</p>

<h3 style="margin-top: 20px">Under 18 Non-custodial sentences:</h3>
<p>
<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">
            Community or youth rehabilitation order
        </summary>
        <div class="article help__text">
            The end of 6 months beginning with the day provided for by or under the order as the last day on which the order is to have effect.
        </div>
    </details>
</div>
<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">
            Fine
        </summary>
        <div class="article help__text">
            The end of 6 months beginning with the date of the relevant conviction.
        </div>
    </details>
</div>
</p>

<h3 style="margin-top: 20px">Compensation Order</h3>
<p>The date on which the payment is made in full</p>

<h3>A relevant order</h3>
<p>(e.g. Conditional Discharge, Bind over to keep the peace, Hospital Order, Supervision or Care Order, Disqualification, disability, prohibition or other penalty - this list is not exhaustive) The day provided for, by or under the order, as the last day on which the order is to have effect.</p>
<p>The convictions of corporate bodies are not subject to the Rehabilitation of Offenders Act 1974.</p>
<p>A later conviction may affect the rehabilitation period for an earlier conviction if it happens before the first period has run out. If you are not sure whether your convictions are “spent”, you should declare it and the traffic commissioner will then consider each case on its merits.</p>

<h3>Applicants for all licence types must declare:</h3>
<p>An offence under the Goods Vehicles (Licensing of Operators) Act 1995</p>
<p>An offence under the Transport Act 1968 or the Road Traffic Act 1960 which relates to licences or means of identification</p>
<p>An offence relating to section 13 of the Hydrocarbon Oil Duties Act 1979 (unlawful use of rebated fuel oil in relation to goods vehicles)</p>
<p>An offence under Section 74 of the Road Traffic Act 1988 (duty to keep inspection records in relation to goods vehicles)</p>

<p>You must also notify the traffic commissioner if any person named in this application, (including partners, directors or transport managers), any company of which a person named on this application is a director, or any parent company if you are a limited company, or any of your employees or agents, has been convicted of any of the following:</p>
<ul>
    <li>An offence under section 53 of the Road Traffic Act 1988 (plating certificates and goods vehicle test certificates)</li>
    <li>An offence in relation to a goods vehicle relating to the maintenance of vehicles in a fit and serviceable condition</li>
    <li>An offence in relation to a goods vehicle relating to speed limits or overloading</li>
    <li>An offence in relation to a goods vehicle relating to the licensing of drivers</li>
    <li>A driver’s hours offence relating to a goods vehicle</li>
    <li>An offence under sections 173 or 174 of the Road Traffic Act 1988 (forgery, false statements or the withholding of information) in relation to an international road haulage permit</li>
    <li>An offence under section 2 of the International Road Haulage Permits Act 1975 (removing, causing, or permitting the removal of a goods vehicle or trailer from the UK in contravention of a prohibition)</li>
    <li>An offence under section 3 of the Control of Pollution Act 1974</li>
    <li>An offence under section 2 of the Refuse Disposal (Amenity) Act 1978</li>
    <li>An offence under section 1 of the Control of Pollution (Amendment) Act 1989</li>
    <li>An offence under section 33 of the Environmental Protection Act 1990</li>
    <li>An offence in relation to a goods vehicle in contravention of a provision prohibiting or restricting waiting vehicles made under the Road Traffic Regulation Act 1984 or a relevant traffic regulation order</li>
</ul>

<h3>Applicants for Standard National and Standard International licences must also declare:</h3>
<p>Any conviction under the law of Northern Ireland or any country outside the United Kingdom which relates to the offences noted above for all applicants and any conviction where one or more of the following punishments was imposed: </p>
<ul>
    <li>Imprisonment exceeding 3 months</li>
    <li>A fine exceeding level 4 on the standard scale</li>
    <li>A community service order (or equivalent) requiring unpaid work for more than 60 hours</li>
    <li>Any punishment outside the UK corresponding to any of the above</li>
</ul>
<p>Any conviction or penalty for an offence under UK law relating to road transport, or any corresponding offence outside the UK. In particular, but not limited to offences relating to:</p>
<ul>
    <li>Drivers’ hours of work and rest periods</li>
    <li>The weights and dimensions of commercial vehicles</li>
    <li>Road and vehicle safety</li>
</ul>
<p>Any conviction or penalty for an offence under UK law relating to road transport, or any corresponding offence outside the UK. In particular:</p>
<ul>
    <li>Exceeding the maximum 6-day or fortnightly driving time limits by margins of 25 % or more.</li>
    <li>Exceeding, during a daily working period, the maximum daily driving time limit by a margin of 50 % or more without taking a break or without an uninterrupted rest period of at least 4.5 hours.</li>
    <li>Not having a tachograph and/or speed limiter, or using a fraudulent device able to modify the records of the recording equipment and/or the speed limiter or falsifying record sheets or data downloaded from the tachograph and/or the driver card. </li>
    <li>Driving without a valid roadworthiness certificate if such a document is required under Community law and/or driving with a very serious deficiency of, among other things, the braking system, the steering linkages, the wheels/tyres, the suspension or chassis that would create such an immediate risk to road safety that it leads to a decision to immobilise the vehicle. </li>
    <li>Transporting dangerous goods that are prohibited for transport or transporting such goods in a prohibited or non-approved means of containment or without identifying them on the vehicle as dangerous goods, thus endangering lives or the environment to such extent that it leads to a decision to immobilise the vehicle. </li>
    <li>Carrying passengers or goods without holding a valid driving licence or carrying by an undertaking not holding a valid Community licence. </li>
    <li>Driving with a driver card that has been falsified, or with a card of which the driver is not the holder, or which has been obtained on the basis of false declarations and/or forged documents.</li>
    <li>Carrying goods exceeding the maximum permissible laden mass by 20 % or more for vehicles the permissible laden weight of which exceeds 12 tonnes, and by 25 % or more for vehicles the permissible laden weight of which does not exceed 12 tonnes. </li>
</ul>

<h4>You must notify any convictions that occur between the date of you applying for a licence and a decision being made on your application.</h4>

<h3>Custodial sentences involving adult offenders</h3>
<p>
<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">
            MORE THAN 30 MONTHS up to, or consisting of 48 MONTHS
        </summary>
        <div class="article help__text">
            The end of the period of 7 years beginning with the day on which the sentence (including any licence period) is completed. Sentences above 48 months are excluded from rehabilitation.
        </div>
    </details>
</div>
<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">
            MORE THAN 6 MONTHS up to, or consisting of 30 MONTHS
        </summary>
        <div class="article help__text">
            The end of the period of 48 months beginning with the day on which the sentence (including any licence period) is completed.
        </div>
    </details>
</div>
<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">
            6 MONTHS or less
        </summary>
        <div class="article help__text">
            The end of the period of 48 months beginning with the day on which the sentence (including any licence period) is complete.
        </div>
    </details>
</div>
</p>

<h3 style="margin-top: 20px">Non-custodial sentences involving adult offenders</h3>
<p>
<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">
            Community or youth rehabilitation order
        </summary>
        <div class="article help__text">
            The end of 12 months beginning with the day provided for by or under the order as the last day on which the order is to have effect.
        </div>
    </details>
</div>
<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">
            Fine
        </summary>
        <div class="article help__text">
            The end of 12 months beginning with the date of the relevant conviction.
        </div>
    </details>
</div>
</p>

<h3 style="margin-top: 20px">Custodial sentences involving offenders under 18</h3>
<p>
<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">
            MORE THAN 30 MONTHS up to, or consisting of 48 MONTHS
        </summary>
        <div class="article help__text">
            The end of the period of 42 months beginning with the day on which the sentence (including any licence period) is completed.
        </div>
    </details>
</div>
<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">
            MORE THAN 6 MONTHS up to, or consisting of 30 MONTHS
        </summary>
        <div class="article help__text">
            The end of the period of 24 months beginning with the day on which the sentence (including any licence period) is completed.
        </div>
    </details>
</div>

<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">
            6 MONTHS or less
        </summary>
        <div class="article help__text">
            The end of the period of 24 months beginning with the day on which the sentence (including any licence period) is completed.
        </div>
    </details>
</div>
</p>

<h3>Under 18 Non-custodial sentences:</h3>
<p>
<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">
            Community or youth rehabilitation order
        </summary>
        <div class="article help__text">
            The end of 6 months beginning with the day provided for by or under the order as the last day on which the order is to have effect.
        </div>
    </details>
</div>
<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">
            Fine
        </summary>
        <div class="article help__text">
            The end of 6 months beginning with the date of the relevant conviction.
        </div>
    </details>
</div>
</p>