<ul class="govuk-list govuk-list--bullet">
    <li>You have read the <a href="<?php echo $this->translate('permits.link.ecmt.guidance') ?>">Guidance Notes</a> on how to use ECMT permits.</li>
    <li>You understand if a permit is issued, it may exclude travel to Austria, Greece, Hungary, Italy and Russia as there are limited numbers of permits for travel to these countries.</li>
    <li>You will only use the appropriate Euro emission standard vehicle that the permit allows.</li>
    <li>You understand that if a permit is issued, you will be issued with a corresponding logbook which you must complete with full journey details before the start of a journey.</li>
    <li>You understand that if a permit is issued, you must obtain a Certificate of Compliance and a Certificate of Roadworthiness for each vehicle and trailer you intend to use.</li>
    <li>Your driver must carry the permit and corresponding logbook, and the certificates for the entire outbound and return journey and present it to any competent authority or inspectors.</li>
</ul>
