<h3><abbv title="European Conference of Ministers of Transport">ECMT</abbv> permit </h3>
<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">Help with ECMT permits</summary>
        <div class="article guidance">
            <p>If you want to transport goods internationally, you can apply for an European Conference of Ministers of Transport (ECMT) permit.</p>
            <p>Further <a href="<?php echo $this->url('permits/ecmt-guidance'); ?>" target="_blank">guidance on ECMT permits</a> is available on GOV.UK.</p>
        </div>
    </details>
</div>