<div class="article js-financial-history">
    <h3>Additional information</h3>
    <p class="form-hint">Give more information about any prior insolvency (min 150 characters).</p>
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false"> What we need to know:</summary>
        <div class="help__text">
            <ul>
                <li>how the insolvency came about</li>
                <li>when it happened</li>
                <li>who was involved</li>
                <li>which courts were involved</li>
                <li>which operator's licences were affected, if any</li>
                <li>any other information you think's relevant </li>
            </ul>
            <p class="field">You can also upload your:</p>
            <ul>
                <li>certificate of discharge from bankruptcy</li>
                <li>liquidator's report</li>
                <li>receiver's report</li>
                <li>administrator's report</li>
                <li>disqualification orders</li>
            </ul>
        </div>
    </details>
</div>