<div class="guidance">
  <p>
  You need to demonstrates there are sufficient financial resources to maintain
  the vehicles and run the business.<br/>
  <a href="#">More guidance on financial evidence</a>
  </p>
</div>

<details class="help">
  <summary class="help__summary">
    How is the financial evidence calculated?
  </summary>
  <div class="help__text">
    <p>
      Standard national and international licence applicants will be required to demonstrate
      £<?php echo number_format($standardFirst); ?>
      for the first vehicle and
      £<?php echo number_format($standardAdditional); ?>
      for each additional vehicle they request to be authorised.
    </p>
    <p>
      The rates for restricted licence holders and applicants are
      £<?php echo number_format($restrictedFirst); ?>
      for the first vehicle and
      £<?php echo number_format($restrictedAdditional); ?>
      for each additional authorised vehicle.
    </p>
  </div>
</details>