
  <div class="article">
    <h3 class="important">Important</h3>
    <p>Fees are non-refundable.</p>
    <p>If the details on your operator licence have changed, please update your licence record.</p>
    <p>You must also send your completed, signed continuation document to us, noting any changes you have made, before the continuation date. If you don’t your licence will expire, even if you pay the fee.</p>
  </div><!-- .article -->