<h2 class="govuk-heading-m govuk-!-margin-top-7" style="font-size: 24px !important">Cookies that remember your settings</h2>
<p>These cookies do things like remember your preferences and the choices you make, to personalise your experience of using the service.</p>
<table style="font-size: 16px;">
    <tbody>
    <tr>
        <td>Name</td>
        <td>Purpose</td>
        <td>Expires</td>
    </tr>
    </tbody>
    <tbody>
    <tr>
        <td>langPref</td>
        <td>Used to store your current language preference (Welsh or English)</td>
        <td>10 years</td>
    </tr>
    </tbody>
</table>
