<ul class="govuk-list govuk-list--bullet">
    <li>You have read the <a href="{{ECMT_PERMITS_GUIDANCE_LINK}}" target="_blank">guidance notes</a> on how to use Short-term ECMT permits.</li>
    <li>You will comply fully with the conditions of use under which the permits may be used.</li>
    <li>You understand that this permit is for transiting through EU member states to non-EU countries who are ECMT members, including Switzerland.</li>
    <li>You understand that this permit is for a third cross-trade trip within 7 days.</li>
    <li>You understand that Short-term permits are not valid for Austria.</li>
    <li>You will only use the appropriate Euro emission standard vehicle that the permit allows.</li>
    <li>You understand you must obtain a Certificate of Compliance and a Certificate of Roadworthiness for each vehicle and trailer you intend to use.</li>
    <li>Your driver must carry the permit and corresponding logbook, and the certificates for the entire outbound and return journey and present it to any competent authority or inspectors.</li>
    <li>You understand that Short-term ECMT permits can only be used for 30 consecutive days during the calendar year they have been issued.</li>
    <li>You will complete the paper permit with the start and end dates before starting your journey.</li>
    <li>You understand the logbook must be returned to DVSA within 2 weeks after returning to the UK.</li>
</ul>
