<p>The Transport Manager has provided their details. You’ll need to review and approve them before we can consider your application.</p>

<p><a href="%s" target="_blank" class="download">Review Transport Manager's details</a></p>

<h3>Wrong details</h3>
<p>If the Transport Manager’s details are wrong, you’ll need to contact them to make the changes. They’ll still be able to access their details through the original link.</p>