<p class="important"><b>I understand that:</b></p>
<p>
    <b>
        By continuing I am confirming that the statements in
        this application are true and the supporting evidence is correct and
        understand that it's an offence to make a false declaration. I also agree
        to Vehicle Operator Licensing using my name, address and date of birth
        provided by GOV.UK Verify or a digital identity from another European country.
    </b>
</p>