<div class="newspaper-advert info-box info-box--grey info-box--large-padding">
    <h3>Newspaper advert for Heavy Goods vehicles and trailers</h3>
    <p class="govuk-body">You must:</p>
    <ul class="govuk-list govuk-list--bullet">
        <li>make sure all details match the information in this licence application</li>
        <li>choose a newspaper that covers the area your operating centre is in</li>
        <li>upload/send us a copy of the full page on which your advert appears</li>
        <li>ensure the newspaper name and date of publication are legible on the copy you upload/send</li>
        <li>the date of publication must be in the period from 21 days before to 21 days after you submit your application</li>
        <li>use our <a title="download the advert template" href="%s" target="_blank">advert template (44kb)</a></li>
    </ul>
	<p class="info-box__text">
		<a href="%s" target="_blank">See our guidelines on how to advertise your application<span class="govuk-visually-hidden">, link opens in a new window</span></a> <i class="icon selfserve-external-link"></i></p>
</div>
