<div class="govuk-box-highlight">
    <h1 class="js-title">%s</h1>
    <p>
        You have removed your  <br>
        ECMT permits application number   <br>
        <strong class="heading-medium">%s</strong>
    </p>
</div>
<div class="actions-container">
    <h3 class="heading-small">What happens next</h3>
    <?php echo $this->partial('en_GB/bullets/markup-ecmt-decline-submitted'); ?>
    <br />
    <div class="notice form-group">
        <p>You can still apply for future ECMT Road Haulage permits but will need to start a new application.
            Future application window periods for ECMT permits will be advertised on
            <a href="https://www.gov.uk/guidance/international-authorisations-and-permits-for-road-haulage" target="_blank">Guidance on using ECMT permits.</a>
        </p>
    </div>
</div>
