<?php
    $typeOfLicenceData = [
        [
            ['value' => $this->translate('continuations.type-of-licence.operating-from'), 'header' => true],
            ['value' => $this->typeOfLicence['operatingFrom']]
        ],
        [
            ['value' => $this->translate('continuations.type-of-licence.type-of-operator'), 'header' => true],
            ['value' => $this->typeOfLicence['goodsOrPsv']],
        ],
        [
            ['value' => $this->translate('continuations.type-of-licence.type-of-licence'), 'header' => true],
            ['value' => $this->typeOfLicence['licenceType']]
        ]
    ];
?>
<?php echo $this->partial('partials/checklist-section', ['data' => $typeOfLicenceData]); ?>
