<div class="govuk-phase-banner">
  <p class="govuk-phase-banner__content">
    <strong class="govuk-tag govuk-phase-banner__content__tag">
  beta
</strong>
    <span class="govuk-phase-banner__text">
      <a class="govuk-link" href="{{URL_SMART_SURVEY_IN_PAGE}}" rel="external noreferrer noopener" aria-label="Help us improve this service" target="_blank">
        What did you think of this service? <?php echo $this->escapeHtml($this->translate('link.opens-new-window')); ?>
      </a> (takes 30 seconds)
    </span>
  </p>
</div>

