<p>Your details have been approved by the operator and can’t be changed.</p>
<p>If you haven't already, you need to:</p>
<ul>
    <li><a href="%s" target="_blank">print out your details</a></li>
    <li>co-sign them with an owner or business director</li>
    <li>return them to the Central Licensing Office</li>
</ul>
<p>We'll notify you when we've recieved your details.</p>

<h3 class="important">Important</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur voluptatum suscipit dolorem facere, id quae est! Possimus ipsa tempore libero!</p>
