<details class="help">
    <summary class="help__summary">
        Help with vehicle authorisation
    </summary>
    <div class="article help__text">
        <p>Your total vehicle authorisation can't be:</p>
        <ul>
            <li>less than the number of vehicles you want to keep at your largest operating centre</li>
            <li>more than the total number vehicles you want to keep across all of your operating centres combined</li>
        </ul>
    </div>
</details>