<h3>Data protection</h3>

<p>The Traffic Commissioner or Department for Infrastructure Northern Ireland will use your personal information as part of their work.</p>
<p>They may share it with each other and:</p>
<ul>
    <li>other Traffic Commissioners</li>
    <li>the Department for Transport</li>
    <li>other government departments</li>
    <li>enforcement agencies</li>
</ul>
<p>We may also use it to contact you about user research.</p>
<p>If you apply for a standard licence we’re legally required to add your details to a national register.</p>
<p>We will share anonymised data with Gov.uk on how you used the site.</p>

<p>We will share anonymised data with Gov.uk on how you used the site.</p>

<h3>Cookies</h3>

<p>Our website puts small files called cookies on to your computer.</p>
<p>Cookies collect information about how you browse the site. Like IP addresses they can’t be used to identify you personally.</p>
<p>Cookies help us:</p>
<ul>
    <li>measure how you use the site so we can update and improve it</li>
    <li>remember notifications you’ve seen so we don’t show them to you again</li>
</ul>
<p>Find out more about <a href="http://www.aboutcookies.org">how to manage cookies</a>.</p>

<h4>Which cookies do we use?</h4>

<table>
    <tr>
        <th>Cookie</th>
        <th>What it does</th>
        <th>Expires</th>
    </tr>
    <tr>
        <td>Google Analytics</td>
        <td>Collects information about how you use the site to improve the way in which this site works. <a href="https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage">Read more about Google Analytics cookies</a></td>
        <td>See <a href="https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage">Google’s guide to cookie usage</a></td>
    </tr>
    <tr>
        <td>PHPSESSID</td>
        <td>Stores temporary information between pages to speed up your browsing</td>
        <td>When you close your browser</td>
    </tr>
    <tr>
        <td>secureToken</td>
        <td>Store basic information about your login details</td>
        <td>When you close your browser</td>
    </tr>
    <tr>
        <td>cookie_seen</td>
        <td>Lets us know which banners and pop-ups you’ve seen so we don’t show them to you again</td>
        <td>One month</td>
    </tr>
    <tr>
        <td>langPref</td>
        <td>Shows us whether you’re reading in English or Welsh</td>
        <td>When you clear cookies from your browser</td>
    </tr>
    <tr>
        <td>incap_ses_{ID}</td>
        <td>Stores session identifiers used by our web site security service to protect and enhance the availability of our site</td>
        <td>When you close your browser</td>
    </tr>
    <tr>
        <td>nlbi_{ID}</td>
        <td>Stores session identifiers used by our web site security service to protect and enhance the availability of our site</td>
        <td>When you close your browser</td>
    </tr>
    <tr>
        <td>visid_incap_{ID}</td>
        <td>Stores session identifiers used by our web site security service to protect and enhance the availability of our site</td>
        <td>One year</td>
    </tr>
</table>

<h3>IP addresses</h3>

<p>We use IP addresses to:</p>
<ul>
    <li>monitor trends</li>
    <li>see which pages users visit</li>
    <li>learn how different sections of the population use the site</li>
</ul>
<p>We can’t use your IP address to identify you personally.</p>

<h3>Government services</h3>

<p>Most services we link to are run by different government departments like HMRC or the Home Office.</p>
<p>These services may set other cookies and will have their own cookie policies.</p>
