<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">
            CY - Additional restrictions
        </summary>
        <div class="article help__text">
            <p>Your total vehicle authorisation can't be:</p>
            <ul>
                <li>less than the largest operating centre</li>
                <li>more than the total across all centres</li>
            </ul>
        </div>
    </details>
</div>
