<h2 class="govuk-heading-l">International Road Haulage Permits</h2>
<p class="govuk-body">From 1 November, you will need to use an ECMT permit to transit through EU countries to non-EU
    countries who are ECMT members, including Switzerland, or if you take more than two cross-trade trips within 7 days
    of making an international journey. You must return to the UK (either laden or unladen) after completing
    cross-trade journeys.</p>
<p class="govuk-body">All other EU journeys will remain permit-free.</p>
