<div class="actions-container article guidance-section">
    <h2>Understand how ECMT permits work</h2>
    <p class = "extra-space">ECMT permits require you to:</p>
    <ul>
        <li>have a valid Standard International or Restricted Goods Operator Licence first before applying for an ECMT permit.</li>
        <li>apply for a separate permit for each goods operator licence that you intend to use to transport goods internationally.</li>
        <li>pay a £10.00 non-refundable application fee per every permit you apply for and agree that the £10.00 application fee is strictly non-refundable</li>
        <li>pay an additional £123.00 Permit Issuing fee per permit within very strict payment deadlines if successfully awarded a permit or the permit will be reallocated.</li>
        <li>transport goods using the permit for one calendar year starting from 1 January to 31 December 2019</li>
        <li>understand the UK has only been allocated 1,224 permits so cannot be issued to all applicants due to limited number of permits available.</li>
        <li>use them for only the 43 countries listed above and allow you to transit through these 43 countries to reach another ECMT destination country only.</li>
        <li>understand that the UK Government only has a small number of permits for the following countries Austria (96), Greece (60), Hungary (164), Italy (464) and Russia (16).</li>
        <li>understand they can be transferred vehicle to vehicle within your company only but not between your company and another haulier at all.</li>
        <li>carry a corresponding numbered logbook to accompany your ECMT permit.</li>
        <li>carry the permit and numbered logbook in the vehicle at all times for inspection at any time throughout the whole of your intended journey.</li>
        <li>instruct your driver to enter into your logbook all journey details before the journey begins and record all journeys taken using an ink pen and not pencil.</li>
        <li>detach journey records from your logbook and return them to the <a href="">International Road Haulage Permit Office (IRHPO)</a> within two weeks after the end of each calendar month.</li>
        <li>only use vehicles that meet the Euro 6 standards.</li>
    </ul>

    <p class = "extra-space">ECMT permits cannot be used:</p>
    <ul>
        <li>in more than one vehicle at any one time.</li>
        <li>for transit of ECMT countries on journeys to non-ECMT countries (countries NOT listed above).</li>
        <li>for cabotage journeys at all.</li>
        <li>by an unaccompanied trailer or semi-trailer.</li>
        <li>with vehicles that are only Euro 4 or Euro 5 compliant.</li>
    </ul>

    <p class = "extra-space">ECMT numbered logbooks must:</p>
    <ul>
        <li> only be used with the same corresponding numbered ECMT permit.</li>
        <li> always be carried within the vehicle for the whole duration of the outward and return journey.</li>
        <li> be shown for inspection by any competent authority during any part of your international journey.</li>
        <li> record full journey details by the driver before the journey begins.</li>
        <li> have all recorded journey copies returned to the <a href="">IRHPO</a> within two weeks after the end of each calendar month for auditing.</li>
        <li> all journey details must be written using a permanent ink pen.</li>
    </ul>

    <h2>Check you are eligible</h2>
    <p class = "extra-space">You must:</p>
    <ul>
        <li> have a <a href="">Vehicle Operating Licensing</a> account</li>
        <li> hold a <a href="">Standard International or Restricted Goods Operator’s Licence</a></li>
        <li> meet <a href="">Euro 6 emissions standards</a> for all vehicles you intend to use</li>
        <li> check you are only transporting to the 43 countries listed above</li>
    </ul>

    <h2>Tell us about your business</h2>
    <p class = "extra-space">We must know:</p>
    <ul>
        <li>the percentage of international haulage that your business does using your specified goods operator licence.</li>
        <li>the number of international trips you made in the last 12 months to EU and EEA countries.</li>
        <li>which main sector you primarily transport goods in.</li>
        <li>which countries you intend to transport goods to between the dates of 1 January and 31 December 2019</li>
    </ul>

    <h2>Next steps</h2>
    <p class = "extra-space">We will:</p>
    <ul>
        <li>acknowledge and process your application and £10.00 non-refundable application fee.</li>
        <li>tell you the outcome of your application and if it is successful, partially successful or unsuccessful.</li>
        <li>let you know the result by email.</li>
        <li>take additional payment of the £123.00 Permit Issuing fee per permit (where you have been successful).</li>
    </ul>

    <h2>Successfully awarded permits</h2>
    <p class = "extra-space">You must:</p>
    <ul>
        <li>pay a Permit Issuing fee of £123.00 per permit awarded.</li>
        <li>pay for your allocated permits within 10 calendar days (TBC).</li>
        <li>sign for your permits delivered by first class recorded delivery.</li>
        <li>Must carry both your permit and corresponding logbook throughout the whole duration of your outward and return international journey.</li>
    </ul>

    <h2>Paying for an ECMT permit</h2>
    <p class = "extra-space">You must:</p>
    <ul>
        <li>pay a £10.00 non-refundable fee for every permit that you apply for, irrespective of its outcome to cover processing costs.</li>
        <li>pay an additional £123.00 permit issuing fee for all successful permit applications awarded.</li>
        <li>use a valid credit or debit card</li>
    </ul>

    <h2>If you are not awarded an ECMT permit</h2>
    <p class = "extra-space">You can:</p>
    <ul>
        <li>reapply at a later stage for the following calendar year.</li>
        <li>automatically be reconsidered for future permits if they become available for reallocation for use within 2019.</li>
    </ul>

    <h2>Using ECMT in Northern Ireland </h2>
    <p class = "extra-space">When applying for a permit you need to:</p>
    <ul>
        <li>Exclude journeys to the Republic of Ireland when calculating the number of trips you make internationally if you hold a Northern Ireland operator licence.</li>
        <li>Exclude journeys to the Republic of Ireland when calculating the percentage of international trips you have made in the lasts 12 months, if you hold a Northern Ireland operator licence.</li>
    </ul>
    <p class = "extra-space">When using a permit across the island of Ireland:</p>
    <ul>
        <li>When travelling to the Republic of Ireland (across the island of Ireland) from Northern Ireland using a Northern Ireland operator licence, issued by the Department for Infrastructure NI, you will neither need to apply nor use an ECMT Permit.</li>
        <li>When travelling to the Republic of Ireland from mainland Great Britain using an operator licence, issued by The Office of the Traffic Commissioners, you will still be required to apply and use an ECMT permit. </li>
    </ul>
</div>
