<div class="newspaper-advert info-box info-box--grey info-box--large-padding">
	<h3>Newspaper advert</h3>
	<p class="info-box__icon-wrapper info-box__text">
	    <i class="info-box__icon selfserve-important"></i>
	    You'll need to advertise the application in a local newspaper and send a copy to us.
    </p>
	<p class="info-box__icon-wrapper info-box__text">
		<a href="%s" target="_blank">See our guidelines on how to advertise your application<span class="visuallyhidden">, link opens in a new window</span></a> <i class="icon selfserve-external-link"></i></p>
</div>
