<details class="govuk-details" data-module="govuk-details">
    <summary class="govuk-details__summary">
        <span class="govuk-details__summary-text">
            Help with vehicle authorisation
        </span>
    </summary>
    <div class="govuk-details__text">
        <p>Your total vehicle authorisation can't be:</p>
        <ul class="govuk-list govuk-list--bullet">
            <li>less than the largest operating centre</li>
            <li>more than the total across all centres</li>
        </ul>
    </div>
</details>
