<p class="govuk-body">The application period for Short-term ECMT permits closed as all permits currently available have been issued.</p>
<p class="govuk-body">Future application windows will be advertised along the year.</p>
<p class="govuk-body">Please bookmark and revisit the <a href="{{ECMT_PERMITS_GUIDANCE_LINK}}" target="_blank">International Road Haulage guidance page</a> for future reference and the latest information on permits.</p>
