<p>Norway agreement has different requirements per period. The permits for you to apply will become available accordingly.</p>
<h2 class="govuk-heading-s govuk-!-margin-top-7">Available now</h2>
<p>Between 1 January 2021 and 30 September 2021, you will only require permits if you are carrying out cabotage. During this period, you must use cabotage permits together with a UK Licence for the Community.</p>
<h2 class="govuk-heading-s govuk-!-margin-top-7">Available mid 2021</h2>
<p>From 1 October 2021 onwards, you will require a standard permit if you wish to enter the country and an additional cabotage permit to carry out cabotage. From this point forward a cabotage pemit must be used together with a standard permit to be valid.</p>
<p>Norway permits are valid from the day they are issued until 31 January the following year.</p>
<?php echo $this->translate('markup-irhp-essential-information-cabotage'); ?>
<?php echo $this->partial('partials/irhp-bilateral-fee-table'); ?>
