<p>Your details have been submitted and can’t be changed.</p>
<p>You'll now need to:</p>
<ul>
    <li><a href="%s" target="_blank">print out your details</a></li>
    <li>sign them</li>
    <li>return them to the Central Licensing Office</li>
</ul>
<p>We'll notify you when we've recieved your details.</p>

<h3 class="important">Important</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur voluptatum suscipit dolorem facere, id quae est! Possimus ipsa tempore libero!</p>
