
<span id="typeOfLicence-hint-goods">
    <a
        href="https://www.gov.uk/being-a-goods-vehicle-operator/types-of-licence"
        target="_blank"
    >
    Read more about types of <span class="js-hidden"> goods vehicle </span>licence <span class="visuallyhidden">, link opens in a new window</span><i class="icon selfserve-external-link"></i></a>
</span>
<span class="js-hidden"> or </span>
<span id="typeOfLicence-hint-psv">
    <a
        href="https://www.gov.uk/psv-operator-licences"
        target="_blank"
    >
      <span class="js-hidden">External link</span> Read more about types of <span class="js-hidden"> public service vehicle </span> licence <span class="visuallyhidden">, link opens in a new window</span><i class="icon selfserve-external-link"></i></a>
</span>
