<div class="actions-container article guidance-section">
    <h2>General introduction</h2>
    <ul>
        <li>ECMT permits must be used when using commercial vehicles to transport goods internationally across the EU and EEA.</li>
        <li>Permits must be kept in the vehicle along with a corresponding logbook for the whole duration of the outbound and return international journey.</li>
        <li>This guidance may change depending on the overall outcome of negotiations for exiting the European Union and you will need to refer back to this page regularly.</li>
    </ul>
</div>