<div class="one-third">
    <div class="sidebar" role="complementary">
        <div class="info-box info-box--grey">
            <h3 class="info-box__heading"><?php echo $this->translate('sidebar-guidance-on-permits'); ?></h3>
            <ul class="govuk-list">
                <li>
                    <a class="govuk-link" href="{{ECMT_PERMITS_GUIDANCE_LINK}}" target="_blank">
                        <?php echo $this->translate('sidebar-check-permits-you-need'); ?><span class="govuk-visually-hidden">(link opens in a new window)</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="sidebar" role="complementary">
        <div class="info-box info-box--grey">
            <h3 class="info-box__heading"><?php echo $this->translate('sidebar-more-information'); ?></h3>
            <ul class="govuk-list">
                <li>
                    <a class="govuk-link" href="{{PERMITS_CARRY_OUT_HAULAGE}}" target="_blank">
                        <?php echo $this->translate('sidebar-carry-out-international-haulage'); ?><span class="govuk-visually-hidden">(link opens in a new window)</span>
                    </a>
                </li>
                <li>
                    <a class="govuk-link" href="{{PERMITS_UK_LICENCE_FOR_THE_COMMUNITY}}" target="_blank">
                        <?php echo $this->translate('sidebar-uk-licence-for-the-community'); ?><span class="govuk-visually-hidden">(link opens in a new window)</span>
                    </a>
                </li>
                <li>
                    <a class="govuk-link" href="{{ECMT_PERMITS_FURTHER_GUIDANCE_LINK}}" target="_blank">
                        <?php echo $this->translate('sidebar-ecmt-permits-link'); ?><span class="govuk-visually-hidden">(link opens in a new window)</span>
                    </a>
                </li>
                <li>
                    <a class="govuk-link" href="{{IRHP_REMOVAL_GUIDANCE_LINK}}" target="_blank">
                        <?php echo $this->translate('sidebar-ecmt-removal-permits'); ?><span class="govuk-visually-hidden">(link opens in a new window)</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
