<div class="actions-container article declaration govuk-hint">
    <div class="field">
        <p>By continuing you confirm that:</p>
    </div>
    <ul class="list-bullet">
        <li>the information you’ve given in this application is correct</li>
        <li>you will not carry out cabotage journeys</li>
        <li>you will only use Euro 6 vehicles for international journeys</li>
        <li>you understand that Austria, Greece, Hungary, Italy and Russia have imposed limits on the number of ECMT permits which are available to UK hauliers</li>
    </ul>
</div>
