<p class="govuk-body"><?php echo $this->escapeHtml($this->translate('lgv-undertakings.page.declaration.text1')); ?></p>
<p class="govuk-body"><?php echo $this->escapeHtml($this->translate('lgv-undertakings.page.declaration.text2')); ?></p>

<h2 class="govuk-heading-m"><?php echo $this->escapeHtml($this->translate('lgv-undertakings.page.declaration.heading')); ?></h2>
<p class="govuk-body"><?php echo $this->escapeHtml($this->translate('lgv-undertakings.page.declaration.text3')); ?></p>
<ul class="govuk-list govuk-list--bullet">
  <li><?php echo $this->escapeHtml($this->translate('lgv-undertakings.page.declaration.bullet-1')); ?></li>
</ul>

<?php echo $this->translateReplace(
    'markup-warning-govuk',
    [
        $this->translate('lgv-undertakings.page.declaration.warning'),
    ]
); ?>