<div class="actions-container article guidance-section">
    <h2>Introduction</h2>
    <ul>
        <li>ECMT permits must be used when using commercial vehicles to transport goods internationally across the EU and EEA.</li>
        <li>Permits must be kept in the vehicle along with a corresponding logbook for the whole duration of the outbound and return international journey.</li>
    </ul>
</div>