<?php
use Permits\View\Helper\EcmtSection;
?>

<h3>What happens next</h3>
<ul class="actions-container list--pad">
  <?php echo $this->partial('en_GB/bullets/markup-ecmt-withdraw-confirmation') ?>
</ul>
<br />
<p>
  You can still apply for future ECMT permits but will need to start a fresh application.
  Future application window periods for ECMT permits will be advertised on
  <a href="<?php echo $this->translate('permits.link.ecmt.terms-and-conditions') ?>"  target="_blank">
    Guidance on using ECMT permits
  </a>
</p>
