<div class="one-third">
    <aside class="sidebar" role="complementary">
        <div class="info-box info-box--grey">
            <h3 class="info-box__heading"><?php echo $this->translate('sidebar-more-information'); ?></h3>
            <ul class="links-list">
                <li class="links-list__item">
                    <a href="{{ECMT_PERMITS_GUIDANCE_LINK}}" target="_blank">International authorisations and permits for road haulage</a>
                </li>
                <li class="links-list__item">
                    <a href="<?php echo $this->translate('being-an-operator-link'); ?>" target="_blank">
                        <?php echo $this->translate('sidebar-variation-being-an-operator'); ?>
                    </a>
                </li>
                <li class="links-list__item">
                    <a href="{{ESSENTIALS_ROAD_HAULAGE}}" target="_blank">The essentials of international road haulage</a>
                </li>
                <li class="links-list__item">
                    <a href="<?php echo $this->translate('public-services-link'); ?>" target="_blank">
                        <?php echo $this->translate('sidebar-variation-public-service'); ?>
                    </a>
                </li>
                <li class="links-list__item">
                    <a href="<?php echo $this->translate('vehicle-safety-link'); ?>" target="_blank">
                        <?php echo $this->translate('sidebar-variation-safety-and-maintenance'); ?>
                    </a>
                </li>
            </ul>
        </div>
    </aside>
</div>
