<p class="govuk-body">
    This website is run by DVSA on behalf of the Traffic Commissioners for Great Britain, the Department for Infrastructure Northern Ireland and the International Road Haulage Permits.
</p>

<p class="govuk-body">
    We want as many people as possible to be able to use this website. For example, that means you should be able to:
</p>

<ul class="govuk-list govuk-list--bullet">
    <li>zoom in up to 300% without the text spilling off the screen</li>
    <li>navigate most of the website using just a keyboard</li>
    <li>navigate most of the website using speech recognition software</li>
    <li>listen to most of the website using a screen reader (including the most recent versions of JAWS, NVDA and VoiceOver)</li>
</ul>

<p class="govuk-body">
    The text on the website should also be as simple as possible to understand.
</p>

<p class="govuk-body">
    <a rel="external" title="External link to ability net webpage" href="https://mcmw.abilitynet.org.uk/" class="govuk-link">AbilityNet</a> has advice on making your device easier to use if you have a disability.
</p>

<h2 id="how-accessible-this-website-is" class="govuk-heading-l">How accessible this website is</h2>

<p class="govuk-body">
    We know some parts of this website aren’t fully accessible:
</p>

<ul class="govuk-list govuk-list--bullet">
    <li>some of our controls, content and status messages are hidden or not announced to screen readers and voice input software</li>
    <li>some of our pages are difficult to navigate using just the keyboard or gestural input</li>
    <li>some of our tables are complex and difficult to navigate using a screen reader</li>
    <li>some of our links, buttons and messages are of sizes and/or colours that are difficult to read</li>
    <li>some of our error messages do not provide enough information to enable a user to correct the error</li>
    <li>the structure of some of our pages means that information is not conveyed in a logical order</li>
    <li>we use some custom controls which will be unfamiliar in the way they appear and operate</li>
    <li>our service has a timeout which might interfere with users completing tasks</li>
</ul>

<h2 id="feedback-and-contact-information" class="govuk-heading-l">Feedback and contact information</h2>

<p class="govuk-body">
    If you need information on this website in a different format, or you need assistance using this website call 0300 123 9000
</p>

<h3 id="reporting-accessibility-problems-with-this-website" class="govuk-heading-m">Reporting accessibility problems with this website</h3>

<p class="govuk-body">
    We’re always looking to improve the accessibility of this website. If you find any problems not listed on this page or think we’re not meeting accessibility requirements, contact: <a rel="external" title="mail to link to our dedicated accessibility team" href="mailto:accessibility@vehicle-operator-licensing.service.gov.uk" class="govuk-link">accessibility@vehicle-operator-licensing.service.gov.uk</a> and tell us:
</p>

<ul class="govuk-list govuk-list--bullet">
    <li>the web address (URL) of the content</li>
    <li>the problem that you encountered</li>
</ul>

<h3 id="enforcement-procedure" class="govuk-heading-m">Enforcement procedure</h3>

<p class="govuk-body">
    The Equality and Human Rights Commission (EHRC) is responsible for enforcing the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018 (the ‘accessibility regulations’). If you’re not happy with how we respond to your complaint, <a rel="external" class="govuk-link" title="external link to contact page" href="https://www.equalityadvisoryservice.com/">contact the Equality Advisory and Support Service (EASS)</a>.
</p>
<p class="govuk-body">
    If you are an operator based in Northern Ireland, and you are not not happy with how we respond to your complaint, contact the <a rel="external" class="govuk-link" title="External link to equalities commission webpage" href="https://www.equalityni.org/Home">Equalities Commission for Northern Ireland (ECNI)</a>.
</p>

<h3 id="contacting-us-by-phone-or-visiting-us-in-person" class="govuk-heading-m">Contacting us</h3>

<p class="govuk-body">
    <a rel="external" class="govuk-link" href="https://www.gov.uk/contact-dvsa">Find out how to contact us</a>.
</p>

<h2 id="technical-information-about-this-websites-accessibility" class="govuk-heading-l">Technical information about this website’s accessibility</h2>

<p class="govuk-body">
    DVSA is committed to making its website accessible, in accordance with the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018.
</p>

<p class="govuk-body">
    This website is partially compliant with the <a rel="external" class="govuk-link" title="external link to Web Content Accessibility Guidelines (WCAG) 2.1" href="https://www.w3.org/TR/WCAG21/">Web Content Accessibility Guidelines version 2.1</a> AA standard, due to the non-compliances listed below.
</p>

<h2 id="non-accessible-content" class="govuk-heading-l">Non accessible content</h2>

<p class="govuk-body">
    The content listed below is non-accessible for the following reasons.
</p>

<h3 id="non-compliance-with-the-accessibility-regulations" class="govuk-heading-m">Non compliance with the accessibility regulations</h3>

<p class="govuk-body">
    The following areas of non-compliance exist.
</p>

<p class="govuk-body">
    Some table headers are unlabelled which means that users with impaired vision will not know what should be entered into these fields. This does not meet WCAG 2.1 success criterion 1.3.1 (Information and Relationships). We plan to fix this by March 2022.
</p>

<p class="govuk-body">
    Some pages and documents do not have a level one heading. This impacts users of screen readers. This does not meet WCAG 2.1 success criterion 1.3.1 (Information and Relationships). We plan to fix this by March 2022.
</p>

<p class="govuk-body">
    On some pages, the focus order of the page does not follow the expected task sequence. This does not meet WCAG 2.1 success criterion 1.3.2 (Meaningful Sequence). We plan to fix this by March 2022.
</p>

<p class="govuk-body">
    Some status indicators have a low colour contrast ratio. This does not meet WCAG 2.1 success criterion 1.4.3 (Contrast Minimum). We plan to fix this by March 2022.
</p>

<p class="govuk-body">
    The focus indicator contrast is not sufficient for some users. This does not meet WCAG 2.1 success criterion 1.4.11 (Non-text contrast). We plan to fix this by March 2022.
</p>

<p class="govuk-body">
    The time out rules mean that users may be timed out before they have finished some task sequences. This does not meet WCAG 2.1 success criterion 2.2.1 (Timing adjustable). We plan to investigate and fix this by March 2022.
</p>

<p class="govuk-body">
    Some tables cannot be accessed using swipe gestures on mobile devices. This does not meet WCAG 2.1 success criterion 2.4.3 (Focus Order). We plan to fix this by March 2022.
</p>

<p class="govuk-body">
    Some links are not descriptive including document type, ‘remove this’ This does not meet WCAG 2.1 success criterion 2.4.4 (Link Purpose). We plan to fix this by March 2022.
</p>

<p class="govuk-body">
    Some action buttons do not make it clear to screen reader users which object the action will be applied to. This does not meet WCAG 2.1 success criterion 2.4.6 (Headings and Labels). We plan to fix this by March 2022.
</p>

<p class="govuk-body">
    The select element used in address look-up does not function as expected with arrow keyboard controls. This does not meet WCAG 2.1 success criterion 3.2.2 (On Input). We plan to fix this by March 2022.
</p>

<p class="govuk-body">
    In some places, the in-line error text is ambiguous. This does not meet WCAG 2.1 success criterion 3.3.3 (Error Suggestion). We plan to fix this by March 2022.
</p>

<p class="govuk-body">
    When multiple items of the same type are added, duplicate field IDs are used. This causes screen readers to report the field as unlabelled. This does not meet WCAG 2.1 success criterion 4.1.1 (Parsing). We plan to fix this by March 2022.
</p>

<p class="govuk-body">
    Under some conditions, buttons and controls such as table sorting are hidden from screen readers. This does not meet WCAG 2.1 success criterion 4.1.2 (Name, Role, Value). We plan to fix this by March 2022.
</p>

<p class="govuk-body">
    Some status changes such as the ‘new’ flag for directors are not announced to screen readers. This means some users are unaware of new content on the page. This does not meet WCAG 2.1 success criterion 4.1.3 (Status messages). We plan to fix this by March 2022.
</p>

<h3 id="disproportionate-burden" class="govuk-heading-m">Disproportionate burden</h3>

<p class="govuk-body">
    We intend to make our services compliant with the <a rel="external" class="govuk-link" title="External link to web content accessibility guidelines" href="https://www.w3.org/TR/WCAG21/">Web Content Accessibility Guidelines version 2.1</a> AA standard. We are not claiming disproportionate burden for any part of our accessibility plan.
</p>

<h3 id="content-thats-not-within-the-scope-of-the-accessibility-regulations" class="govuk-heading-m">
    Content that’s not within the scope of the accessibility regulations
</h3>

<p class="govuk-body">
    The accessibility regulations <a class="govuk-link" title="External link to accessibility regulations on PDFs" href="https://www.legislation.gov.uk/uksi/2018/952/regulation/4/made">do not require us to fix PDFs or other documents published before 23 September 2018</a> if they’re not essential to providing our services.
</p>

<p class="govuk-body">
    Any new PDFs or Word documents we publish will meet accessibility standards.
</p>

<h2 id="preparation-of-this-accessibility-statement" class="govuk-heading-l">
    Preparation of this accessibility statement
</h2>

<p class="govuk-body">
    This statement was prepared on 10/08/2020. It was last updated on 31/03/2021.
</p>

<p class="govuk-body">
    This website was last tested on 13-17 January 2020 by The Digital Accessibility Centre (DAC).
</p>

<p class="govuk-body">
    We used this approach to decide a sample of pages to test:
</p>

<ul class="govuk-list govuk-list--bullet">
    <li>our highest volume transaction (vehicle changes)</li>
    <li>all sections of the ‘Manage my licence’ user journey (which duplicates the main pages of the ‘Apply for a licence’ journey</li>
    <li>journeys we know cause problems for users (change operating centre and vehicle authorisation, reviewing the submission)</li>
    <li>links to external pages containing further advice</li>
    <li>critical pages underpinning compliance (the document/correspondence section of the website)</li>
</ul>

<p class="govuk-body">
    Our public search pages and internal caseworker pages were tested internally using GDS guidance and insights from the independent accessibility audit conducted by DAC.
</p>
