<p>Because the Transport Manager doesn't have an email address they'll have to:</p>
<ul>
    <li><b><a href="<?php echo $this->translate('TM1_FORM_LINK') ?>" download>download a TM1 form (PDF 150KB)</a></b></li>
    <li>co-sign it with an owner or business director</li>
    <li>return it to the Central Licensing Office</li>
</ul>
<p>We’ll let you know when we’ve received their form.</p>

<h3 class="important">Important</h3>
<p><?php echo $this->translate('lva.section.title.transport-manager-application.important') ?></p>