<div class="hint space">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">What is an international trip?</summary>
        <div class="article guidance">
            <ul>
                <li>from a place in the United Kingdom to a place in the territory of European Union or in a relevant country or passing through that territory or country;</li>
                <li>between places outside the United Kingdom where one or both of which are situated in the territory of the European Union or in a relevant country, regardless of whether that journey passes through the United Kingdom; or</li>
                <li>between places outside the United Kingdom and the territory of the European Union or a relevant country, but passing through the territory of the European Union or a relevant country, regardless of whether that journey passes through the United Kingdom;</li>
            </ul>
        </div>
    </details>
</div>