<h3>Traffic Commissioners for Great Britain: privacy notice</h3>

<p>The Traffic Commissioners’ fair processing notice tells you what you can expect when a traffic commissioner of Great Britain (the data controller) collects your data. A traffic commissioner will use your personal information as part of their work as the competent authority for assessing access to the occupation of road transport operators.</p>
<p>You can access the fair processing notice here: <a href="https://www.gov.uk/government/publications/traffic-commissioners-for-great-britain-privacy-notice">https://www.gov.uk/government/publications/traffic-commissioners-for-great-britain-privacy-notice</a>.</p>
<p>Alternatively you may request a paper copy by telephoning 0300 123 9000.</p>


<h3>Department for Infrastructure Northern Ireland: privacy notice</h3>

<p>The Goods Vehicle Operator Licensing privacy notice tells you what you can expect when the Department for Infrastructure (the data controller) collects your data. The Department will use your personal information as part of their work for assessing access to the occupation of goods vehicle operators.</p>
<p>You can access the privacy notice here: <a href="https://www.infrastructure-ni.gov.uk/sites/default/files/publications/infrastructure/goods-vehicle-operator-licensing-northern-ireland-privacy-notice.pdf">https://www.infrastructure-ni.gov.uk/sites/default/files/publications/infrastructure/goods-vehicle-operator-licensing-northern-ireland-privacy-notice.pdf.</a></p>
<p>Alternatively you may request a paper copy by telephoning 0300 200 7831.</p>