<p>Morocco has 4 types of permit. If you need more than one permit type, you will have to apply for each one separately.</p>

<h2 class="govuk-heading-s govuk-!-margin-top-7">Standard multiple journey permits</h2>
<p>This will allow 15 return journeys within a calendar year.</p>

<h2 class="govuk-heading-s govuk-!-margin-top-7">Standard single journey permits</h2>
<p>This will allow one outward and one return journey within 3 months of the date of issue.</p>

<h2 class="govuk-heading-s govuk-!-margin-top-7">Hors contingent permits (single journey)</h2>
<p>This is required for taking in filming equipment for film or TV productions, or equipment for exhibitions. It is valid for one outward and return journey within 3 months from the date of issue.</p>

<h2 class="govuk-heading-s govuk-!-margin-top-7">Empty entry permits (single journey)</h2>
<p>This will allow you to enter Morocco empty to collect a load. It is valid for one outward and one return journey within 3 months from the date of issue.</p>

<h2 class="govuk-heading-s govuk-!-margin-top-7">Fees</h2>

<table class="govuk-table">
    <thead class="govuk-table__head">
    <tr class="govuk-table__row">
        <th class="govuk-table__header" scope="col"><?php echo $this->escapeHtml($this->translate('permits.page.fee.permit.type')); ?></th>
        <th class="govuk-table__header" scope="col"><?php echo $this->escapeHtml($this->translate('permits.page.fee.total.fee.per.permit')); ?></th>
    </tr>
    </thead>
    <tbody class="govuk-table__body">
    <tr class="govuk-table__row">
        <td class="govuk-table__cell">Standard multiple journey permit</td>
        <td class="govuk-table__cell"><?php echo $this->currencyFormatter(50); ?></td>
    </tr>
    <tr class="govuk-table__row">
        <td class="govuk-table__cell">Standard single journey permit</td>
        <td class="govuk-table__cell"><?php echo $this->currencyFormatter(8); ?></td>
    </tr>
    <tr class="govuk-table__row">
        <td class="govuk-table__cell">Hors contingent (single journey)</td>
        <td class="govuk-table__cell"><?php echo $this->currencyFormatter(8); ?></td>
    </tr>
    <tr class="govuk-table__row">
        <td class="govuk-table__cell">Empty entry (single journey)</td>
        <td class="govuk-table__cell"><?php echo $this->currencyFormatter(8); ?></td>
    </tr>
    </tbody>
</table>

<p>This amount includes the application and issuing fees.</p>

