<div class="one-third">
    <aside class="sidebar" role="complementary">
        <div class="info-box info-box--permit">
            <h3 class="info-box__heading">More information</h3>
            <ul class="links-list">
                <li class="links-list__item">
                    <a href="https://www.gov.uk/guidance/international-authorisations-and-permits-for-road-haulage" target="_blank">International authorisations and permits for road haulage</a>
                </li>
                <li class="links-list__item">
                    <a href="https://www.gov.uk/being-a-goods-vehicle-operator" target="_blank">Being a goods vehicle operator</a>
                </li>
                <li class="links-list__item">
                    <a href="https://www.gov.uk/guidance/the-essentials-of-international-road-haulage" target="_blank">The essentials of international road haulage</a>
                </li>
                <li class="links-list__item">
                    <a href="https://www.gov.uk/psv-operator-licences" target="_blank">Public Service Vehicle operator licences</a></a>
                </li>
                <li class="links-list__item">
                    <a href="#" target="_blank">Vehicle safety and maintenance guides</a>
                </li>
            </ul>
        </div>
    </aside>
</div>
