<details class="help">
  <summary class="help__summary">
    What's the difference?
  </summary>
  <div class="help__text">
    <p>
     You need a goods vehicle operator's licence if your business uses goods vehicles above a certain weight.
     <a href="https://www.gov.uk/being-a-goods-vehicle-operator/overview">Being a goods vehicle operator</a>
    </p>
    <p>You need a public service vehicle (PSV) operator's licence to:</p>
    <ul>
      <li>operate a vehicle for hire or reward (payment or payment in kind) that can carry 9 or more passengers</li>
      <li>operate a smaller vehicle carrying passengers and charging separate fares for the journey</li>
    </ul>
    <p>More information about <a href="https://www.gov.uk/government/publications/psv-operator-licensing-a-guide-for-operators-psv437">PSV operator licensing</a></p>
  </div>
</details>