<details class="help">
    <summary class="help__summary">
        Calculate your average balance
    </summary>
    <div class="article help__text">
        Get your most recent closing balance, then go backwards in 10 day steps using the same dates on each month,
        to exactly 3 months earlier. This gives 10 figures, which are added and then divided by 10 to give the
        average balance.
    </div>
</details>