<div class="info-box info-box--large-padding info-box--grey">
	<h3>Next steps</h3>
	<p class="info-box__text">Your Transport Manager will need to complete a paper
    <a href="<?php echo $this->url('getfile', ['identifier' => base64_encode($this->translate('tm-add-user-no-email-document-identifier'))]); ?>" download target="_blank">TM1 form.</a>
	</p>
	<p class="important info-box__text">The licence application can not be considered until a TM1 form has been received by the Central Licensing Office.</p>
</div>
