<h3 class="important">Next steps</h3>
<p>A link to an online form will be sent to the provided email address for the Transport Manager to complete.</p>
<p>You will be notified when the Transport Manager has submitted their details for your approval.</p>
<p>
    <b>Please note:</b> The licence application can not be considered until all transport manager's details have been
    approved by a Director or owner of the business.
</p>