<p>Hi %s,</p>

<p>
    <strong>%s</strong> have named you as a Transport Manager on the Vehicle Operator Licence
    <strong>%s/%s</strong>.
</p>

<p>
    <a href="%s">Sign in to your account</a>
</p>

<p>
    Experiencing problems?<br>
    If you are unable to access the form online using the link above, this help guide provides answers to
    frequently asked questions. You can also contact us at <a href="mailto:notifications@vehicle-operator-licensing.service.gov.uk">notifications@vehicle-operator-licensing.service.gov.uk</a>
    If for whatever reason you are unable to complete the Transport Manager form online, you can download a
    paper copy of the <a href="https://www.gov.uk/government/publications/application-to-add-a-transport-manager-to-a-licence-tm1">TM1 form here</a>. You will need to complete the TM1 form and mail it to us.
</p>