<div class="article js-financial-history">
    <h3>Additonal information</h3>
    <p>Give more information about any prior insolvency (min 200 characters).<br />You can also upload evidence, such as legal documents, below.</p>
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false"> What do you need to tell us about?</summary>
        <div class="help__text">
            <p>Let us know:</p>
            <ul>
                <li>how the insolvency came about</li>
                <li>when it happened</li>
                <li>who was involved</li>
                <li>which courts were involved</li>
                <li>which operator's licences were affected, if any</li>
                <li>any other information you think's relevant </li>
            </ul>
            <p>You should also upload your:</p>
            <ul>
                <li>certificate of discharge from bankruptcy</li>
                <li>liquidator's report</li>
                <li>receiver's report</li>
                <li>administrator's report</li>
                <li>disqualification orders</li>
            </ul>
        </div>
    </details>
</div>