<div class="hint">
    <details class="help">
        <summary class="help__summary" role="button" aria-expanded="false">
            Additional restrictions
        </summary>
        <div class="article help__text">
            <ul class="guide">
                <li>Austria, Greece, Hungary, Italy and Russia impose additional restrictions on the use of <abbr title="European Conference of Ministers of Transport">ECMT permits and only allow limited numbers of ECMT permits into their country.</abbr></li>
                <li>If you are transporting goods to Austria, Italy, Greece, Hungary or Russia you must ensure your permit number is within the range that the country allows. For example, Greece allows only 60 <abbr title="European Conference of Ministers of Transport">ECMT permits so you can only travel to Greece if your permit is number 000001 to 000060.</abbr></li>
                <li>If you are transporting goods to Russia you may wish to <a href="https://www.gov.uk/government/publications/general-quota-application" target="blank">apply for a bilateral permit</a></li>
            </ul>
        </div>
    </details>
</div>