<div class="gem-c-govspeak govuk-govspeak govuk-!-margin-top-7" data-module="govspeak">
    <h2 class="govuk-heading-m" style="font-size: 24px !important">IP addresses</h2>
    <p>Vehicle Operator Licensing collects IP address to track and aggregate non-personal information. For example, the service uses IP addresses to monitor trends, regions from which users navigate the website and pages visited.</p>
    <p>We can’t use your IP address to identify you personally.</p>
</div>
