<p>Sorry, we're having technical problems. Please try again in a few minutes.</p>
<p>If the page still doesn't work email <a href="mailto:operatorlicensing@otc.gsi.gov.uk">operatorlicensing@otc.gsi.gov.uk</a>.</p>
<p>Let us know:</p>
<ul>
    <li>which page you were visiting</li>
    <li>what you were trying to do</li>
    <?php if (!empty($id)): ?>
        <li>quoting reference <?php echo $this->escapeHtml($id); ?></li>
    <?php endif; ?>
</ul>
