<div tabindex="0" id="more-actions__button__container" onkeydown="open__actions__button__container()" onfocus="close__actions__button__container()" onfocusout="close__actions__button__container()" role="button" aria-expanded="false" class="more-actions">
  <div id="more-actions__button" class="more-actions__button" role="button">{{label}}</div>
  <div class="more-actions__list">
    {{content}}
  </div>
</div>
