<div class="table__header"<?php
    echo !empty($this->object->getVariable('id')) ?
    ' id="' . $this->object->getVariable('id') .'"' : '' ?>>
    <?php if ($this->object->renderTotal()) { ?><h3><?php echo $this->object->renderTotal(); ?> {{title}}</h3><?php } ?>
    <?php echo $this->object->renderActions(); ?>
</div>
<?php echo $this->object->renderLayout('table'); ?>
<?php echo $this->object->renderFooter();
