<div class="table__header"<?php
    echo !empty($this->object->getVariable('id')) ?
    ' id="' . $this->object->getVariable('id') .'"' : '' ?>>
    <h3>
        <?php
        if ($this->object->renderTotal()) {
            echo $this->object->renderTotal();
        }
        ?>
        <?php echo $this->getEscaper()->escapeHtml($this->object->getVariable('title')); ?>
    </h3>
    <?php echo $this->object->renderActions(); ?>
</div>
<?php echo $this->object->renderLayout('table'); ?>
<?php echo $this->object->renderFooter();
