<div class="table__footer">
    <?php if ($this->object->getTotal() > $this->object->getLimit()): ?>
    <div class="results-settings">
        <p><?php echo $this->translate('pagination.showing');?>:</p>
        <ul class="results-settings__list">
            <?php echo $this->object->renderLimitOptions(); ?>
        </ul><!-- end .results-settings__list -->
        <p><?php echo $this->translate('pagination.results-per-page');?></p>
    </div><!-- end .results-settings -->

    <ul class="pagination right-aligned" role="navigation">
        <?php echo $this->object->renderPageOptions(); ?>
    </ul><!-- end .pagination.right-aligned -->
    <?php endif; ?>
</div>