<div class="table__footer">
    <div class="results-settings">
        <p>Showing:</p>
        <ul class="results-settings__list">
            <?php echo $this->renderLimitOptions(); ?>
        </ul><!-- end .results-settings__list -->
        <p>results per page</p>
    </div><!-- end .results-settings -->

    <ul class="pagination right-aligned" role="navigation">
        <?php //echo $this->renderPageOptions(); ?>
    </ul><!-- end .pagination.right-aligned -->
</div>