<div class="table__wrapper">
    <table <?php echo $this->object->renderAttributes($this->object->getAttributes()); ?>>
        <thead>
            <tr>
                <?php
                foreach ($this->object->getColumns() as $column) {
                    echo $this->object->renderHeaderColumn($column, '{{[elements/th]}}');
                }
                ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->object->getRows() as $row) { ?>
                <tr <?php if ($this->object->isRowDisabled($row)): ?>class="disabled"<?php endif; ?>>
                    <?php
                    foreach ($this->object->getColumns() as $column) {
                        echo $this->object->renderBodyColumn($row, $column, '{{[elements/td]}}');
                    }
                    ?>
                </tr>
                <?php
            }

            echo $this->object->renderExtraRows();
            ?>
        </tbody>
        <?php echo $this->object->renderTableFooter(); ?>
    </table>
</div>