<?php
//if we have a date, only try to format if it isn't blank
if (array_key_exists('date', $item)) {
    if ($item['date']) {
        $item['value'] = $this->dateFormat(
            \DateTime::createFromFormat(
                \DateTime::ISO8601,
                $item['date']
            ),
            \IntlDateFormatter::SHORT
        );
    } else {
        $item['value'] = '';
    }
}

//convert values into yes or no
switch ($item['value']) {
    case 'Y':
        $item['value'] = 'Yes';
        break;
    case 'N':
        $item['value'] = 'No';
        break;
}

?>
<li class="definition-list__item<?php echo (isset($item['class']) ? ' ' . $item['class'] : ''); ?>">
    <dt><?php echo $this->translate($item['label']); ?></dt>
    <dd>
        <?php if (isset($item['url']) && $item['url'] != ''): ?>
            <a href="<?php echo $item['url']; ?>"><?php echo (isset($item['noEscape']) ? $item['value'] : $this->escapeHtml($item['value'])); ?></a>
        <?php else: ?>
            <?php echo (isset($item['noEscape']) ? $item['value'] : $this->escapeHtml($item['value'])); ?>
        <?php endif; ?>
    </dd>
</li>
