<?php

/**
 * Section Access Test
 *
 * @author Rob Caiger <rob@clocal.co.uk>
 */
namespace CommonComponentTest\Lav;

use CommonTest\Bootstrap;
use PHPUnit_Framework_TestCase;
use Common\Service\Data\SectionConfig;
use Common\Service\Entity\LicenceEntityService;

/**
 * Section Access Test
 *
 * @author Rob Caiger <rob@clocal.co.uk>
 */
class SectionAccessTest extends PHPUnit_Framework_TestCase
{
    /**
     * @group component
     * @group lva_component
     * @group section_access_lva_component
     * @dataProvider providerSectionAccessExternalApplication
     */
    public function testSectionAccessExternalApplication($access, $expected)
    {
        $serviceManager = Bootstrap::getServiceManager();

        $sectionConfig = new SectionConfig();
        $inputSections = $sectionConfig->getAll();

        $accessHelper = $serviceManager->get('Helper\Access');
        $accessibleSections = $accessHelper->setSections($inputSections)->getAccessibleSections($access);

        $this->assertEquals($expected, array_keys($accessibleSections));
    }

    public function providerSectionAccessExternalApplication()
    {
        return array(
            // EXTERNAL APPLICATION
            array(
                // Goods Standard National
                array(
                    'external',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'transport_managers',
                    'vehicles',
                    'safety',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties'
                )
            ),
            array(
                // Goods Standard International
                array(
                    'external',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'transport_managers',
                    'vehicles',
                    'safety',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties'
                )
            ),
            array(
                // Goods Restricted
                array(
                    'external',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'vehicles',
                    'safety',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties'
                )
            ),
            array(
                // PSV Standard National
                array(
                    'external',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'transport_managers',
                    'vehicles_psv',
                    'vehicles_declarations',
                    'safety',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties'
                )
            ),
            array(
                // PSV Standard International
                array(
                    'external',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'transport_managers',
                    'vehicles_psv',
                    'vehicles_declarations',
                    'safety',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties'
                )
            ),
            array(
                // PSV Restricted
                array(
                    'external',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'vehicles_psv',
                    'vehicles_declarations',
                    'safety',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties'
                )
            ),
            array(
                // PSV Special Restricted
                array(
                    'external',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_SPECIAL_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'taxi_phv'
                )
            ),
            // INTERNAL APPLICATION
            array(
                // Goods Standard National
                array(
                    'internal',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'transport_managers',
                    'vehicles',
                    'safety',
                    'conditions_undertakings',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties'
                )
            ),
            array(
                // Goods Standard International
                array(
                    'internal',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'transport_managers',
                    'vehicles',
                    'safety',
                    'conditions_undertakings',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties'
                )
            ),
            array(
                // Goods Restricted
                array(
                    'internal',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'vehicles',
                    'safety',
                    'conditions_undertakings',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties'
                )
            ),
            array(
                // PSV Standard National
                array(
                    'internal',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'transport_managers',
                    'vehicles_psv',
                    'vehicles_declarations',
                    'safety',
                    'conditions_undertakings',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties'
                )
            ),
            array(
                // PSV Standard International
                array(
                    'internal',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'transport_managers',
                    'vehicles_psv',
                    'vehicles_declarations',
                    'safety',
                    'conditions_undertakings',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties'
                )
            ),
            array(
                // PSV Restricted
                array(
                    'internal',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'financial_evidence',
                    'vehicles_psv',
                    'vehicles_declarations',
                    'safety',
                    'conditions_undertakings',
                    'financial_history',
                    'licence_history',
                    'convictions_penalties'
                )
            ),
            array(
                // PSV Special Restricted
                array(
                    'internal',
                    'application',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_SPECIAL_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'taxi_phv'
                )
            ),
            // EXTERNAL LICENCE
            array(
                // Goods Standard National
                array(
                    'external',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            array(
                // Goods Standard International
                array(
                    'external',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles',
                    'community_licences',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            array(
                // Goods Restricted
                array(
                    'external',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'vehicles',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            array(
                // PSV Standard National
                array(
                    'external',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles_psv',
                    'discs',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            array(
                // PSV Standard International
                array(
                    'external',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles_psv',
                    'discs',
                    'community_licences',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            array(
                // PSV Restricted
                array(
                    'external',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'vehicles_psv',
                    'discs',
                    'community_licences',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            array(
                // PSV Special Restricted
                array(
                    'external',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_SPECIAL_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'taxi_phv'
                )
            ),
            // INTERNAL LICENCE
            array(
                // Goods Standard National
                array(
                    'internal',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            array(
                // Goods Standard International
                array(
                    'internal',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles',
                    'community_licences',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            array(
                // Goods Restricted
                array(
                    'internal',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'vehicles',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            array(
                // PSV Standard National
                array(
                    'internal',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles_psv',
                    'discs',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            array(
                // PSV Standard International
                array(
                    'internal',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles_psv',
                    'discs',
                    'community_licences',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            array(
                // PSV Restricted
                array(
                    'internal',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'vehicles_psv',
                    'discs',
                    'community_licences',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            array(
                // PSV Special Restricted
                array(
                    'internal',
                    'licence',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_SPECIAL_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'taxi_phv'
                )
            ),
            // EXTERNAL VARIATION
            array(
                // Goods Standard National
                array(
                    'external',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            array(
                // Goods Standard International
                array(
                    'external',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles',
                    'community_licences',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            array(
                // Goods Restricted
                array(
                    'external',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'vehicles',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            array(
                // PSV Standard National
                array(
                    'external',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles_psv',
                    'discs',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            array(
                // PSV Standard International
                array(
                    'external',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles_psv',
                    'discs',
                    'community_licences',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            array(
                // PSV Restricted
                array(
                    'external',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'vehicles_psv',
                    'discs',
                    'community_licences',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            // INTERNAL VARIATION
            array(
                // Goods Standard National
                array(
                    'internal',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            array(
                // Goods Standard International
                array(
                    'internal',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles',
                    'community_licences',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            array(
                // Goods Restricted
                array(
                    'internal',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_GOODS_VEHICLE,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'vehicles',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            array(
                // PSV Standard National
                array(
                    'internal',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_NATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles_psv',
                    'discs',
                    'safety',
                    'conditions_undertakings'
                )
            ),
            array(
                // PSV Standard International
                array(
                    'internal',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_STANDARD_INTERNATIONAL
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'transport_managers',
                    'vehicles_psv',
                    'discs',
                    'community_licences',
                    'safety',
                    'conditions_undertakings',
                )
            ),
            array(
                // PSV Restricted
                array(
                    'internal',
                    'variation',
                    LicenceEntityService::LICENCE_CATEGORY_PSV,
                    LicenceEntityService::LICENCE_TYPE_RESTRICTED
                ),
                array(
                    'type_of_licence',
                    'business_details',
                    'addresses',
                    'people',
                    'operating_centres',
                    'vehicles_psv',
                    'discs',
                    'community_licences',
                    'safety',
                    'conditions_undertakings'
                )
            )
        );
    }
}
