<form method="POST" action="">
    <div class="table__header">
        <h3>Appeal</h3>
        <div class="actions-container">
            <a href="<?php echo $this->record['editHref']; ?>" class="action--primary" />Edit</a>
            <a href="<?php echo $this->record['deleteHref']; ?>" class="action--warning" />Delete</a>
        </div>
        <p>
            <strong>Appeal deadline:</strong><br />
            <?php echo date('d/m/y', strtotime($this->record['deadlineDate'])); ?>
        </p>
        <p>
            <strong>Date of appeal:</strong><br />
            <?php echo date('d/m/y', strtotime($this->record['appealDate'])); ?>
        </p>
        <p>
            <strong>Appeal number:</strong><br />
            <?php echo $this->appeal['appealNumber']; ?>
        </p>
        <p>
            <strong>Reason:</strong><br />
            <?php echo $this->record['reason']; ?>
        </p>
        <p>
            <strong>Outline ground:</strong><br />
            <?php echo $this->record['outlineGround']; ?>
        </p>
        <p>
            <strong>Date set for appeal hearing:</strong><br />
            <?php echo date('d/m/y', strtotime($this->record['hearingDate'])); ?>
        </p>
        <p>
            <strong>Date of decision:</strong><br />
            <?php echo date('d/m/y', strtotime($this->record['decisionDate'])); ?>
        </p>
        <p>
            <strong>Papers due at tribunal:</strong><br />
            <?php echo date('d/m/y', strtotime($this->record['papersDue'])); ?>
        </p>
        <p>
            <strong>Papers sent:</strong><br />
            <?php echo date('d/m/y', strtotime($this->record['papersSent'])); ?>
        </p>
        <p>
            <strong>Outcome:</strong><br />
            <?php echo $this->record['outcome']; ?>
        </p>
        <p>
            <strong>Comments:</strong><br />
            <?php echo $this->record['comment']; ?>
        </p>
    </div>
</form>