<div class="table__header">
    <h3>Appeal</h3>
    <div class="actions-container">
        <a href="<?php echo $this->url('case_appeal', array('action' => 'edit', 'appeal' => $this->record['id']), array(), true); ?>" class="action--primary" />Edit</a>
        <a href="<?php echo ''; ?>" class="action--warning" />Delete</a>
    </div>
    <?php
        echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Appeal deadline', 'content' => $this->record['deadlineDate']));
        echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Date of appeal', 'content' => $this->record['appealDate']));
        echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Appeal number', 'content' => $this->record['appealNumber']));
        echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Reason', 'content' => $this->translate('appeal_reason.' . $this->record['reason'])));
        echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Outline ground', 'content' => $this->record['outlineGround']));
        echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Date set for appeal hearing', 'content' => $this->record['hearingDate']));
        echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Date of decision', 'content' => $this->record['decisionDate']));
        echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Papers due at tribunal', 'content' => $this->record['papersDue']));
        echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Papers sent', 'content' => $this->record['papersSent']));
        
        if ($this->record['outcome'] > 0) {
            echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Outcome', 'content' => $this->translate('appeal_outcome.' . $this->record['outcome'])));
        } else {
            echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Outcome', 'content' => ''));
        }
        
        if ($this->record['isWithdrawn'] == 'Y') {
            echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Withdrawn', 'content' => $this->record['withdrawnDate']));
        }
        
        echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Comments', 'content' => $this->record['comment']));
    ?>
</div>