<div class="table__header">
    <h3>Appeal</h3>
    <div class="actions-container">
        <a href="<?php echo $this->url('case_appeal', array('action' => 'edit', 'id' => $this->record['id']), array(), true); ?>" class="action--primary" />Edit</a>
        <a href="<?php echo $this->url('case_appeal', array('action' => 'delete', 'id' => $this->record['id']), array(), true);; ?>" class="action--secondary" />Delete</a>
    </div>
    <?php
    echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Appeal deadline', 'content' => $this->record['deadlineDate']));
    echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Date of appeal', 'content' => $this->record['appealDate']));
    echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Appeal number', 'content' => $this->record['appealNo']));
    echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Reason', 'content' => $this->translate($this->record['reason']['description'])));
    echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Outline ground', 'content' => $this->record['outlineGround']));
    echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Date set for appeal hearing', 'content' => $this->record['hearingDate']));
    echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Date of decision', 'content' => $this->record['decisionDate']));
    echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Papers due at tribunal', 'content' => $this->record['papersDueDate']));
    echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Papers sent', 'content' => $this->record['papersSentDate']));
    if (!empty($this->record['outcome'])) {
        echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Outcome', 'content' => $this->translate($this->record['outcome']['description'])));
    } else {
        echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Outcome', 'content' => ''));
    }
    echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Comments', 'content' => $this->record['comment']));

    if ($this->record['withdrawnDate'] != null) {
        echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Withdrawn', 'content' => $this->record['withdrawnDate']));
    }
    ?>
</div>