<form method="POST" action="<?php echo $this->stay['formAction']; ?>">
    <?php //echo $this->stayType['edit']; ?>
    <div class="table__header">
        <h3><?php echo $this->stayType; ?></h3>
        <div class="actions-container">
            <a href="<?php echo $this->stay['editHref']; ?>" class="action--primary" />Edit</a>
            <a href="<?php echo $this->stay['deleteHref']; ?>" class="action--warning" />Delete</a>
        </div>
        <?php
            echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Date of decision:', 'content' => 'dd/mm/yyyy'));
            echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Date of request:', 'content' => $this->stay['requestDate']));
            echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Outcome:', 'content' => $this->stay['outcome']));
            echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Notes:', 'content' => $this->stay['notes']));
        ?>
    </div>
</form>