<div class="table__header">
    <h3><?php echo $this->stayType; ?> Stay</h3>
    <div class="actions-container">
        <a href="<?php echo $this->url('case_stay_action', array('action' => 'edit', 'stayType' => $this->stay['stayType'], 'stay' => $this->stay['id']), array(), true); ?>" class="action--primary" />Edit</a>
        <a href="<?php echo ''; ?>" class="action--warning" />Delete</a>
    </div>
    <?php
        echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Date of decision', 'content' => 'dd/mm/yyyy'));
        echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Date of request', 'content' => $this->stay['requestDate']));
        echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Outcome', 'content' => $this->translate($this->stay['outcome'])));
        echo $this->render('partials/case/summary-row.phtml', array('heading' => 'Notes', 'content' => $this->stay['notes']));
    ?>
</div>