<form method="POST" action="<?php echo $this->stay['formAction']; ?>">
    <?php //echo $this->stayType['edit']; ?>
    <div class="table__header">
        <h3><?php echo $this->stayType; ?></h3>
        <div class="actions-container">
            <a href="<?php echo $this->stay['editHref']; ?>" class="action--primary" />Edit</a>
            <a href="<?php echo $this->stay['deleteHref']; ?>" class="action--warning" />Delete</a>
        </div>
        <p>
            <strong>Date of decision:</strong><br />
            <?php echo 'dd/mm/yy'; ?>
        </p>
        <p>
            <strong>Date of request:</strong><br />
            <?php echo date('d/m/y', strtotime($this->stay['requestDate'])); ?>
        </p>
        <p>
            <strong>Outcome:</strong><br />
            <?php echo $this->stay['outcome']; ?>
        </p>
        <p>
            <strong>Notes:</strong><br />
            <?php echo $this->stay['notes']; ?>
        </p>
    </div>
</form>