<ul class="list-bullet">
  <li>I have read the Guidance Notes concerning ECMT permits.</li>

  <li>I will comply fully with the conditions under which the permits may be used.</li>

  <li>I understand if a permit is issued it may include restrictions to Austria, Greece, Hungary, Italy and Russia.</li>

  <li>You must carry and complete the correct matching logbook and permit for the entire outbound and return journey.</li>
</ul>
