<ul class="govuk-list govuk-list--bullet">
    <li>You have read the <a href="<?php echo $this->translate('permits.link.ecmt.guidance') ?>">Guidance Notes</a> on how to use international road haulage permits.</li>
    <li>You will comply fully with the conditions of use and terms and conditions under which the permits may be used.</li>
    <li>Your driver will carry the permit for the entire outbound and return journey and present it to any competent authority or inspectors.</li>
    <li>You understand that one permit is required to transport goods to and from each EU and EEA country.</li>
</ul>
