<?php

use Common\Form\Elements\Types\AbstractInputSearch;
use Common\Form\Elements\Types\PlainText;
use Zend\Form\Element\Button;
use Zend\Form\Element\Text;

/** @var AbstractInputSearch $fieldsetElement */
/** @var PlainText $hintElement */
$hintElement = $fieldsetElement->get(AbstractInputSearch::ELEMENT_HINT_NAME);
/** @var Text $inputElement */
$inputElement = $fieldsetElement->get(AbstractInputSearch::ELEMENT_INPUT_NAME);
/** @var Button $submitElement */
$submitElement = $fieldsetElement->get(AbstractInputSearch::ELEMENT_SUBMIT_NAME);

$fieldSetName = $this->escapeHtmlAttr($fieldsetElement->getName());
$inputName = $this->escapeHtmlAttr($inputElement->getAttribute('name'));
$submitName = $this->escapeHtmlAttr($submitElement->getAttribute('name'));
$error = array_values($fieldsetElement->getMessages(AbstractInputSearch::ELEMENT_INPUT_NAME))[0];

?>

<div class="<?php echo !empty($error) ? "validation-wrapper" : ""; ?>">
    <fieldset class="lookup" data-group="<?php echo $fieldSetName; ?>">
        <label class="govuk-label" for="<?php echo $inputName ?>"><?php echo $this->escapeHtml($this->translate($fieldsetElement->getOption('label'))); ?></label>
        <div class="field hint">
            <?php echo $this->escapeHtml($this->translate($hintElement->getOption('value'))); ?>
        </div>
        <?php if (!empty($error)) : ?>
            <span class="govuk-error-message"><span class="govuk-visually-hidden"><?php echo $this->translate('Error'); ?>:</span><?php echo $error ?></span>
        <?php endif; ?>
        <div class="field inline">
            <input name="<?php echo $inputName; ?>" data-container-class="inline" id="<?php echo $inputName; ?>" type="text" value="<?php echo $this->escapeHtml($inputElement->getValue()); ?>">
        </div>
        <div class="field inline">
            <button type="submit" name="<?php echo $submitName; ?>" class="action--primary" data-container-class="inline"
                    id="<?php echo $submitName; ?>" value="">
                <?php echo $this->escapeHtml($this->translate($submitElement->getLabel())) ?>
            </button>
        </div>
    </fieldset>
</div>
