<?php
/** @var Common\Form\Elements\Types\RadioHorizontal $element */
$element = $this->element;

/** @var \Zend\Form\Element\Radio $radioElement */
$radioElement = $element->get('yesNo');
$errors = $this->formElementErrors()->render($element);
$hasValidationError = !empty($errors);
?>

<div class="<?php echo ($hasValidationError) ? 'validation-wrapper' : 'field' ?>">
    <fieldset class="radio-button__fieldset">
        <?php if ($hasValidationError) : ?>
            <?php echo $errors ?>
        <?php endif; ?>

        <legend><?php echo $this->translate($element->getLabel()) ?></legend>

        <?php if ($element->getOption('hint')) : ?>
            <p class="form-hint"><?php echo $this->translate($element->getOption('hint')) ?></p>
        <?php endif; ?>

        <div class="radio-button__container radio-button__container--inline">
            <?php echo $this->formRadioOption($radioElement, 'Y') ?>
        </div>
        <div class="radio-button__container radio-button__container--inline">
            <?php echo $this->formRadioOption($radioElement, 'N') ?>
        </div>

        <?php if ($element->has('yesContent')) : ?>
            <?php
            $id = $radioElement->getValueOptions()['Y']['attributes']['id'] .'_content';
            ?>
            <div class="radio-button__hidden-content help__text" id="<?php echo $id ?>">
                <?php
                $yesContentElement = $element->get('yesContent');
                if ($yesContentElement instanceof \Zend\Form\Fieldset) {
                    echo $this->formCollection($yesContentElement, false);
                } else {
                    echo $this->formRow($yesContentElement);
                }
                ?>
            </div>
        <?php endif; ?>

        <?php if ($element->has('noContent')) : ?>
            <?php
            $id = $radioElement->getValueOptions()['N']['attributes']['id'] .'_content';
            ?>
            <div class="radio-button__hidden-content help__text" id="<?php echo $id ?>">
                <?php
                $noContentElement = $element->get('noContent');
                if ($noContentElement instanceof \Zend\Form\Fieldset) {
                    echo $this->formCollection($noContentElement, false);
                } else {
                    echo $this->formRow($noContentElement);
                }
                ?>
            </div>
        <?php endif; ?>
    </fieldset>
</div>
