<?php
/** @var Common\Form\Elements\Types\RadioHorizontal $element */
$element = $this->element;

/** @var \Zend\Form\Element\Radio $radioElement */
$radioElement = $element->get('radio');
$errors = $this->formElementErrors()->render($radioElement);
$hasValidationError = !empty($errors);
?>

<div class="<?php echo ($hasValidationError) ? 'validation-wrapper' : 'field' ?>">
    <fieldset class="radio-button__fieldset">
        <legend>
            <?php echo $this->translate($element->getLabel()) . $this->translate($radioElement->getLabel()); ?>
        </legend>

        <?php if ($element->getOption('hint')) : ?>
            <p class="form-hint"><?php echo $this->translate($element->getOption('hint')) ?></p>
        <?php endif; ?>

        <?php if ($hasValidationError) : ?>
            <?php echo $errors ?>
        <?php endif; ?>

        <?php foreach ($radioElement->getValueOptions() as $valueOption) : ?>
            <div class="radio-button__container">
                <?php echo $this->formRadioOption($radioElement, $valueOption['value']) ?>
            </div>

            <?php
            $contentElementName = $valueOption['value'] .'Content';
            if ($element->has($contentElementName)) {
                echo $this->render(
                    'partials/form/radio-content',
                    array_merge(
                        $this->vars()->getArrayCopy(),
                        [
                            'element' => $element->get($contentElementName),
                            'id' => $valueOption['attributes']['id'] .'_content',
                        ]
                    )
                );
            }
            ?>
        <?php endforeach; ?>

    </fieldset>
</div>

<?php
if ($element->has('submit')) {
    echo $this->formRow($element->get('submit'));
}
?>
