<?php
/** @var Common\Form\Elements\Types\RadioHorizontal $element */
$element = $this->element;

/** @var \Zend\Form\Element\Radio $radioElement */
$radioElementName = $element->getOption('radio-element') ?? 'radio';
$radioElement = $element->get($radioElementName);
$errors = $this->formElementErrors()->render($radioElement);
$hasValidationError = !empty($errors);
$dataGroup = $element->getOption('fieldset-data-group');
$dataGroupAttribute = empty($dataGroup) ? '' : 'data-group="' . $dataGroup . '"';
?>

<div class="<?php echo ($hasValidationError) ? 'field error__wrapper' : 'field' ?>">
    <fieldset class="radio-button__fieldset radio-button__fieldset--vertical" <?php echo $dataGroupAttribute; ?>>
        <legend class="<?php echo $element->getLabelAttributes()['class']; ?>">
            <?php echo $this->translate($element->getLabel()); ?>
        </legend>

        <?php if ($element->getOption('hint')) : ?>
            <p class="form-hint"><?php echo $this->translate($element->getOption('hint')) ?></p>
        <?php endif; ?>

        <?php if ($hasValidationError) : ?>
            <?php echo $errors ?>
        <?php endif; ?>
        <?php
        foreach ($radioElement->getValueOptions() as $valueOption) {
            echo $this->formRadioOption($radioElement, $valueOption['value']);
            $contentElementName = $valueOption['value'] . 'Content';
            if ($element->has($contentElementName)) {
                echo $this->render(
                    'partials/form/radio-content',
                    array_merge(
                        $this->vars()->getArrayCopy(),
                        [
                            'element' => $element->get($contentElementName),
                            'id' => $valueOption['attributes']['id'] .'_content',
                        ]
                    )
                );
            }
        }
        ?>
    </fieldset>
</div>

<?php
if ($element->has('submit')) {
    echo $this->formRow($element->get('submit'));
}
?>
