<?php

if ($element->has('warning')) {
    echo $this->formRow($element->get('warning'));
}

if ($element->has('warningVisible')) {
    echo $this->formRow($element->get('warningVisible'));
}

/** @var Common\Form\Elements\Types\RadioHorizontal $element */
$element = $this->element;

$errors = $this->formElementErrors()->render($this->radioElement);
$hasValidationError = !empty($errors);
$dataGroup = $element->getOption('fieldset-data-group');
$dataGroupAttribute = empty($dataGroup) ? '' : 'data-group="' . $dataGroup . '"';
?>

<div class="<?php echo ($hasValidationError) ? 'field error__wrapper' : 'field' ?>">
    <fieldset class="radio-button__fieldset radio-button__fieldset--vertical" <?php echo $dataGroupAttribute; ?>>
        <legend class="<?php echo $element->getLabelAttributes()['class'] ?? ''; ?>">
            <?php echo $this->translate($element->getLabel()); ?>
        </legend>

        <?php if ($element->getOption('hint')) : ?>
            <p class="form-hint"><?php echo $this->translate($element->getOption('hint')) ?></p>
        <?php endif; ?>

        <?php if ($hasValidationError) : ?>
            <?php echo $errors ?>
        <?php endif; ?>
        <?php foreach ($this->valueOptions as $key => $valueOption) { ?>
            <?php echo $this->formRadioOption($this->radioElement, $key); ?>
            <?php echo $this->partial(new \Common\Form\View\Model\FormRadioContentViewModel($valueOption)); ?>
        <?php } ?>
    </fieldset>
</div>

<?php
if ($element->has('submit')) {
    echo $this->formRow($element->get('submit'));
}
?>
